// source: ei.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.ei.ContractCoopStatusUpdateRequest');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.ei.BasicRequestInfo');
goog.require('proto.ei.FarmProductionParams');
goog.require('proto.ei.PlayerFarmInfo');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ei.ContractCoopStatusUpdateRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ei.ContractCoopStatusUpdateRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ei.ContractCoopStatusUpdateRequest.displayName = 'proto.ei.ContractCoopStatusUpdateRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.ei.ContractCoopStatusUpdateRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ei.ContractCoopStatusUpdateRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ei.ContractCoopStatusUpdateRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    rinfo: (f = msg.getRinfo()) && proto.ei.BasicRequestInfo.toObject(includeInstance, f),
    userId: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    contractIdentifier: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    coopIdentifier: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
    pushUserId: (f = jspb.Message.getField(msg, 8)) == null ? undefined : f,
    amount: (f = jspb.Message.getOptionalFloatingPointField(msg, 4)) == null ? undefined : f,
    rate: (f = jspb.Message.getOptionalFloatingPointField(msg, 5)) == null ? undefined : f,
    timeCheatsDetected: (f = jspb.Message.getField(msg, 6)) == null ? undefined : f,
    soulPower: (f = jspb.Message.getOptionalFloatingPointField(msg, 7)) == null ? undefined : f,
    eop: (f = jspb.Message.getField(msg, 15)) == null ? undefined : f,
    boostTokens: (f = jspb.Message.getField(msg, 9)) == null ? undefined : f,
    boostTokensSpent: (f = jspb.Message.getField(msg, 13)) == null ? undefined : f,
    hideCcStatus: (f = jspb.Message.getBooleanField(msg, 17)) == null ? undefined : f,
    productionParams: (f = msg.getProductionParams()) && proto.ei.FarmProductionParams.toObject(includeInstance, f),
    farmInfo: (f = msg.getFarmInfo()) && proto.ei.PlayerFarmInfo.toObject(includeInstance, f),
    eggLayingRateBuff: jspb.Message.getFloatingPointFieldWithDefault(msg, 10, 1.0),
    earningsBuff: jspb.Message.getFloatingPointFieldWithDefault(msg, 11, 1.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ei.ContractCoopStatusUpdateRequest}
 */
proto.ei.ContractCoopStatusUpdateRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ei.ContractCoopStatusUpdateRequest;
  return proto.ei.ContractCoopStatusUpdateRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ei.ContractCoopStatusUpdateRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ei.ContractCoopStatusUpdateRequest}
 */
proto.ei.ContractCoopStatusUpdateRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 12:
      var value = new proto.ei.BasicRequestInfo;
      reader.readMessage(value,proto.ei.BasicRequestInfo.deserializeBinaryFromReader);
      msg.setRinfo(value);
      break;
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setContractIdentifier(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setCoopIdentifier(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setPushUserId(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setAmount(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setRate(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setTimeCheatsDetected(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setSoulPower(value);
      break;
    case 15:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setEop(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setBoostTokens(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setBoostTokensSpent(value);
      break;
    case 17:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setHideCcStatus(value);
      break;
    case 14:
      var value = new proto.ei.FarmProductionParams;
      reader.readMessage(value,proto.ei.FarmProductionParams.deserializeBinaryFromReader);
      msg.setProductionParams(value);
      break;
    case 16:
      var value = new proto.ei.PlayerFarmInfo;
      reader.readMessage(value,proto.ei.PlayerFarmInfo.deserializeBinaryFromReader);
      msg.setFarmInfo(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setEggLayingRateBuff(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setEarningsBuff(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ei.ContractCoopStatusUpdateRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ei.ContractCoopStatusUpdateRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ei.ContractCoopStatusUpdateRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRinfo();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      proto.ei.BasicRequestInfo.serializeBinaryToWriter
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 8));
  if (f != null) {
    writer.writeString(
      8,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeDouble(
      5,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeUint32(
      6,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeDouble(
      7,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 15));
  if (f != null) {
    writer.writeUint32(
      15,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 9));
  if (f != null) {
    writer.writeUint32(
      9,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 13));
  if (f != null) {
    writer.writeUint32(
      13,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 17));
  if (f != null) {
    writer.writeBool(
      17,
      f
    );
  }
  f = message.getProductionParams();
  if (f != null) {
    writer.writeMessage(
      14,
      f,
      proto.ei.FarmProductionParams.serializeBinaryToWriter
    );
  }
  f = message.getFarmInfo();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      proto.ei.PlayerFarmInfo.serializeBinaryToWriter
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 10));
  if (f != null) {
    writer.writeDouble(
      10,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 11));
  if (f != null) {
    writer.writeDouble(
      11,
      f
    );
  }
};


/**
 * optional BasicRequestInfo rinfo = 12;
 * @return {?proto.ei.BasicRequestInfo}
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.getRinfo = function() {
  return /** @type{?proto.ei.BasicRequestInfo} */ (
    jspb.Message.getWrapperField(this, proto.ei.BasicRequestInfo, 12));
};


/**
 * @param {?proto.ei.BasicRequestInfo|undefined} value
 * @return {!proto.ei.ContractCoopStatusUpdateRequest} returns this
*/
proto.ei.ContractCoopStatusUpdateRequest.prototype.setRinfo = function(value) {
  return jspb.Message.setWrapperField(this, 12, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ei.ContractCoopStatusUpdateRequest} returns this
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.clearRinfo = function() {
  return this.setRinfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.hasRinfo = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional string user_id = 1;
 * @return {string}
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.getUserId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ei.ContractCoopStatusUpdateRequest} returns this
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.setUserId = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.ei.ContractCoopStatusUpdateRequest} returns this
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.clearUserId = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.hasUserId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string contract_identifier = 2;
 * @return {string}
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.getContractIdentifier = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.ei.ContractCoopStatusUpdateRequest} returns this
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.setContractIdentifier = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.ei.ContractCoopStatusUpdateRequest} returns this
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.clearContractIdentifier = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.hasContractIdentifier = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string coop_identifier = 3;
 * @return {string}
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.getCoopIdentifier = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.ei.ContractCoopStatusUpdateRequest} returns this
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.setCoopIdentifier = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.ei.ContractCoopStatusUpdateRequest} returns this
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.clearCoopIdentifier = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.hasCoopIdentifier = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string push_user_id = 8;
 * @return {string}
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.getPushUserId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.ei.ContractCoopStatusUpdateRequest} returns this
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.setPushUserId = function(value) {
  return jspb.Message.setField(this, 8, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.ei.ContractCoopStatusUpdateRequest} returns this
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.clearPushUserId = function() {
  return jspb.Message.setField(this, 8, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.hasPushUserId = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional double amount = 4;
 * @return {number}
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.getAmount = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.ei.ContractCoopStatusUpdateRequest} returns this
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.setAmount = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.ei.ContractCoopStatusUpdateRequest} returns this
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.clearAmount = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.hasAmount = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional double rate = 5;
 * @return {number}
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.getRate = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.ei.ContractCoopStatusUpdateRequest} returns this
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.setRate = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.ei.ContractCoopStatusUpdateRequest} returns this
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.clearRate = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.hasRate = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional uint32 time_cheats_detected = 6;
 * @return {number}
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.getTimeCheatsDetected = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.ei.ContractCoopStatusUpdateRequest} returns this
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.setTimeCheatsDetected = function(value) {
  return jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.ei.ContractCoopStatusUpdateRequest} returns this
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.clearTimeCheatsDetected = function() {
  return jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.hasTimeCheatsDetected = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional double soul_power = 7;
 * @return {number}
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.getSoulPower = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 7, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.ei.ContractCoopStatusUpdateRequest} returns this
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.setSoulPower = function(value) {
  return jspb.Message.setField(this, 7, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.ei.ContractCoopStatusUpdateRequest} returns this
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.clearSoulPower = function() {
  return jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.hasSoulPower = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional uint32 eop = 15;
 * @return {number}
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.getEop = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 15, 0));
};


/**
 * @param {number} value
 * @return {!proto.ei.ContractCoopStatusUpdateRequest} returns this
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.setEop = function(value) {
  return jspb.Message.setField(this, 15, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.ei.ContractCoopStatusUpdateRequest} returns this
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.clearEop = function() {
  return jspb.Message.setField(this, 15, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.hasEop = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional uint32 boost_tokens = 9;
 * @return {number}
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.getBoostTokens = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.ei.ContractCoopStatusUpdateRequest} returns this
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.setBoostTokens = function(value) {
  return jspb.Message.setField(this, 9, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.ei.ContractCoopStatusUpdateRequest} returns this
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.clearBoostTokens = function() {
  return jspb.Message.setField(this, 9, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.hasBoostTokens = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional uint32 boost_tokens_spent = 13;
 * @return {number}
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.getBoostTokensSpent = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {number} value
 * @return {!proto.ei.ContractCoopStatusUpdateRequest} returns this
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.setBoostTokensSpent = function(value) {
  return jspb.Message.setField(this, 13, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.ei.ContractCoopStatusUpdateRequest} returns this
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.clearBoostTokensSpent = function() {
  return jspb.Message.setField(this, 13, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.hasBoostTokensSpent = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional bool hide_cc_status = 17;
 * @return {boolean}
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.getHideCcStatus = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 17, false));
};


/**
 * @param {boolean} value
 * @return {!proto.ei.ContractCoopStatusUpdateRequest} returns this
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.setHideCcStatus = function(value) {
  return jspb.Message.setField(this, 17, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.ei.ContractCoopStatusUpdateRequest} returns this
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.clearHideCcStatus = function() {
  return jspb.Message.setField(this, 17, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.hasHideCcStatus = function() {
  return jspb.Message.getField(this, 17) != null;
};


/**
 * optional FarmProductionParams production_params = 14;
 * @return {?proto.ei.FarmProductionParams}
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.getProductionParams = function() {
  return /** @type{?proto.ei.FarmProductionParams} */ (
    jspb.Message.getWrapperField(this, proto.ei.FarmProductionParams, 14));
};


/**
 * @param {?proto.ei.FarmProductionParams|undefined} value
 * @return {!proto.ei.ContractCoopStatusUpdateRequest} returns this
*/
proto.ei.ContractCoopStatusUpdateRequest.prototype.setProductionParams = function(value) {
  return jspb.Message.setWrapperField(this, 14, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ei.ContractCoopStatusUpdateRequest} returns this
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.clearProductionParams = function() {
  return this.setProductionParams(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.hasProductionParams = function() {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * optional PlayerFarmInfo farm_info = 16;
 * @return {?proto.ei.PlayerFarmInfo}
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.getFarmInfo = function() {
  return /** @type{?proto.ei.PlayerFarmInfo} */ (
    jspb.Message.getWrapperField(this, proto.ei.PlayerFarmInfo, 16));
};


/**
 * @param {?proto.ei.PlayerFarmInfo|undefined} value
 * @return {!proto.ei.ContractCoopStatusUpdateRequest} returns this
*/
proto.ei.ContractCoopStatusUpdateRequest.prototype.setFarmInfo = function(value) {
  return jspb.Message.setWrapperField(this, 16, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ei.ContractCoopStatusUpdateRequest} returns this
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.clearFarmInfo = function() {
  return this.setFarmInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.hasFarmInfo = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * optional double egg_laying_rate_buff = 10;
 * @return {number}
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.getEggLayingRateBuff = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 10, 1.0));
};


/**
 * @param {number} value
 * @return {!proto.ei.ContractCoopStatusUpdateRequest} returns this
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.setEggLayingRateBuff = function(value) {
  return jspb.Message.setField(this, 10, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.ei.ContractCoopStatusUpdateRequest} returns this
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.clearEggLayingRateBuff = function() {
  return jspb.Message.setField(this, 10, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.hasEggLayingRateBuff = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional double earnings_buff = 11;
 * @return {number}
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.getEarningsBuff = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 11, 1.0));
};


/**
 * @param {number} value
 * @return {!proto.ei.ContractCoopStatusUpdateRequest} returns this
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.setEarningsBuff = function(value) {
  return jspb.Message.setField(this, 11, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.ei.ContractCoopStatusUpdateRequest} returns this
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.clearEarningsBuff = function() {
  return jspb.Message.setField(this, 11, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ei.ContractCoopStatusUpdateRequest.prototype.hasEarningsBuff = function() {
  return jspb.Message.getField(this, 11) != null;
};


