// source: ei.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.ei.SetArtifactRequest');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.ei.ArtifactInventoryItem');
goog.require('proto.ei.ArtifactSpec');
goog.require('proto.ei.BasicRequestInfo');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ei.SetArtifactRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ei.SetArtifactRequest.repeatedFields_, null);
};
goog.inherits(proto.ei.SetArtifactRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ei.SetArtifactRequest.displayName = 'proto.ei.SetArtifactRequest';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ei.SetArtifactRequest.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ei.SetArtifactRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.ei.SetArtifactRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ei.SetArtifactRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ei.SetArtifactRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    rinfo: (f = msg.getRinfo()) && proto.ei.BasicRequestInfo.toObject(includeInstance, f),
    artifact: (f = msg.getArtifact()) && proto.ei.ArtifactInventoryItem.toObject(includeInstance, f),
    stonesList: jspb.Message.toObjectList(msg.getStonesList(),
    proto.ei.ArtifactSpec.toObject, includeInstance),
    goldPricePaid: (f = jspb.Message.getOptionalFloatingPointField(msg, 4)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ei.SetArtifactRequest}
 */
proto.ei.SetArtifactRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ei.SetArtifactRequest;
  return proto.ei.SetArtifactRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ei.SetArtifactRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ei.SetArtifactRequest}
 */
proto.ei.SetArtifactRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.ei.BasicRequestInfo;
      reader.readMessage(value,proto.ei.BasicRequestInfo.deserializeBinaryFromReader);
      msg.setRinfo(value);
      break;
    case 2:
      var value = new proto.ei.ArtifactInventoryItem;
      reader.readMessage(value,proto.ei.ArtifactInventoryItem.deserializeBinaryFromReader);
      msg.setArtifact(value);
      break;
    case 3:
      var value = new proto.ei.ArtifactSpec;
      reader.readMessage(value,proto.ei.ArtifactSpec.deserializeBinaryFromReader);
      msg.addStones(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setGoldPricePaid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ei.SetArtifactRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ei.SetArtifactRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ei.SetArtifactRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ei.SetArtifactRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRinfo();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.ei.BasicRequestInfo.serializeBinaryToWriter
    );
  }
  f = message.getArtifact();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.ei.ArtifactInventoryItem.serializeBinaryToWriter
    );
  }
  f = message.getStonesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.ei.ArtifactSpec.serializeBinaryToWriter
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeDouble(
      4,
      f
    );
  }
};


/**
 * optional BasicRequestInfo rinfo = 1;
 * @return {?proto.ei.BasicRequestInfo}
 */
proto.ei.SetArtifactRequest.prototype.getRinfo = function() {
  return /** @type{?proto.ei.BasicRequestInfo} */ (
    jspb.Message.getWrapperField(this, proto.ei.BasicRequestInfo, 1));
};


/**
 * @param {?proto.ei.BasicRequestInfo|undefined} value
 * @return {!proto.ei.SetArtifactRequest} returns this
*/
proto.ei.SetArtifactRequest.prototype.setRinfo = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ei.SetArtifactRequest} returns this
 */
proto.ei.SetArtifactRequest.prototype.clearRinfo = function() {
  return this.setRinfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ei.SetArtifactRequest.prototype.hasRinfo = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional ArtifactInventoryItem artifact = 2;
 * @return {?proto.ei.ArtifactInventoryItem}
 */
proto.ei.SetArtifactRequest.prototype.getArtifact = function() {
  return /** @type{?proto.ei.ArtifactInventoryItem} */ (
    jspb.Message.getWrapperField(this, proto.ei.ArtifactInventoryItem, 2));
};


/**
 * @param {?proto.ei.ArtifactInventoryItem|undefined} value
 * @return {!proto.ei.SetArtifactRequest} returns this
*/
proto.ei.SetArtifactRequest.prototype.setArtifact = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ei.SetArtifactRequest} returns this
 */
proto.ei.SetArtifactRequest.prototype.clearArtifact = function() {
  return this.setArtifact(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ei.SetArtifactRequest.prototype.hasArtifact = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated ArtifactSpec stones = 3;
 * @return {!Array<!proto.ei.ArtifactSpec>}
 */
proto.ei.SetArtifactRequest.prototype.getStonesList = function() {
  return /** @type{!Array<!proto.ei.ArtifactSpec>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ei.ArtifactSpec, 3));
};


/**
 * @param {!Array<!proto.ei.ArtifactSpec>} value
 * @return {!proto.ei.SetArtifactRequest} returns this
*/
proto.ei.SetArtifactRequest.prototype.setStonesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.ei.ArtifactSpec=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ei.ArtifactSpec}
 */
proto.ei.SetArtifactRequest.prototype.addStones = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.ei.ArtifactSpec, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ei.SetArtifactRequest} returns this
 */
proto.ei.SetArtifactRequest.prototype.clearStonesList = function() {
  return this.setStonesList([]);
};


/**
 * optional double gold_price_paid = 4;
 * @return {number}
 */
proto.ei.SetArtifactRequest.prototype.getGoldPricePaid = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.ei.SetArtifactRequest} returns this
 */
proto.ei.SetArtifactRequest.prototype.setGoldPricePaid = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.ei.SetArtifactRequest} returns this
 */
proto.ei.SetArtifactRequest.prototype.clearGoldPricePaid = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ei.SetArtifactRequest.prototype.hasGoldPricePaid = function() {
  return jspb.Message.getField(this, 4) != null;
};


