// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ei.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ei;

@kotlin.jvm.JvmName("-initializeartifactsDB")
public inline fun artifactsDB(block: ei.ArtifactsDBKt.Dsl.() -> kotlin.Unit): ei.Ei.ArtifactsDB =
  ei.ArtifactsDBKt.Dsl._create(ei.Ei.ArtifactsDB.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ei.ArtifactsDB`
 */
public object ArtifactsDBKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ei.Ei.ArtifactsDB.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: ei.Ei.ArtifactsDB.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): ei.Ei.ArtifactsDB = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class InventoryItemsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .ei.ArtifactInventoryItem inventory_items = 1;`
     */
     public val inventoryItems: com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactInventoryItem, InventoryItemsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.inventoryItemsList
      )
    /**
     * `repeated .ei.ArtifactInventoryItem inventory_items = 1;`
     * @param value The inventoryItems to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addInventoryItems")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactInventoryItem, InventoryItemsProxy>.add(value: ei.Ei.ArtifactInventoryItem) {
      _builder.addInventoryItems(value)
    }
    /**
     * `repeated .ei.ArtifactInventoryItem inventory_items = 1;`
     * @param value The inventoryItems to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignInventoryItems")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactInventoryItem, InventoryItemsProxy>.plusAssign(value: ei.Ei.ArtifactInventoryItem) {
      add(value)
    }
    /**
     * `repeated .ei.ArtifactInventoryItem inventory_items = 1;`
     * @param values The inventoryItems to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllInventoryItems")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactInventoryItem, InventoryItemsProxy>.addAll(values: kotlin.collections.Iterable<ei.Ei.ArtifactInventoryItem>) {
      _builder.addAllInventoryItems(values)
    }
    /**
     * `repeated .ei.ArtifactInventoryItem inventory_items = 1;`
     * @param values The inventoryItems to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllInventoryItems")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactInventoryItem, InventoryItemsProxy>.plusAssign(values: kotlin.collections.Iterable<ei.Ei.ArtifactInventoryItem>) {
      addAll(values)
    }
    /**
     * `repeated .ei.ArtifactInventoryItem inventory_items = 1;`
     * @param index The index to set the value at.
     * @param value The inventoryItems to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setInventoryItems")
    public operator fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactInventoryItem, InventoryItemsProxy>.set(index: kotlin.Int, value: ei.Ei.ArtifactInventoryItem) {
      _builder.setInventoryItems(index, value)
    }
    /**
     * `repeated .ei.ArtifactInventoryItem inventory_items = 1;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearInventoryItems")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactInventoryItem, InventoryItemsProxy>.clear() {
      _builder.clearInventoryItems()
    }


    /**
     * `optional uint64 item_sequence = 2;`
     */
    public var itemSequence: kotlin.Long
      @JvmName("getItemSequence")
      get() = _builder.itemSequence
      @JvmName("setItemSequence")
      set(value) {
        _builder.itemSequence = value
      }
    /**
     * `optional uint64 item_sequence = 2;`
     */
    public fun clearItemSequence() {
      _builder.clearItemSequence()
    }
    /**
     * `optional uint64 item_sequence = 2;`
     * @return Whether the itemSequence field is set.
     */
    public fun hasItemSequence(): kotlin.Boolean {
      return _builder.hasItemSequence()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class InventorySlotsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .ei.InventorySlot inventory_slots = 3;`
     */
     public val inventorySlots: com.google.protobuf.kotlin.DslList<ei.Ei.InventorySlot, InventorySlotsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.inventorySlotsList
      )
    /**
     * `repeated .ei.InventorySlot inventory_slots = 3;`
     * @param value The inventorySlots to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addInventorySlots")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.InventorySlot, InventorySlotsProxy>.add(value: ei.Ei.InventorySlot) {
      _builder.addInventorySlots(value)
    }
    /**
     * `repeated .ei.InventorySlot inventory_slots = 3;`
     * @param value The inventorySlots to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignInventorySlots")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ei.Ei.InventorySlot, InventorySlotsProxy>.plusAssign(value: ei.Ei.InventorySlot) {
      add(value)
    }
    /**
     * `repeated .ei.InventorySlot inventory_slots = 3;`
     * @param values The inventorySlots to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllInventorySlots")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.InventorySlot, InventorySlotsProxy>.addAll(values: kotlin.collections.Iterable<ei.Ei.InventorySlot>) {
      _builder.addAllInventorySlots(values)
    }
    /**
     * `repeated .ei.InventorySlot inventory_slots = 3;`
     * @param values The inventorySlots to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllInventorySlots")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ei.Ei.InventorySlot, InventorySlotsProxy>.plusAssign(values: kotlin.collections.Iterable<ei.Ei.InventorySlot>) {
      addAll(values)
    }
    /**
     * `repeated .ei.InventorySlot inventory_slots = 3;`
     * @param index The index to set the value at.
     * @param value The inventorySlots to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setInventorySlots")
    public operator fun com.google.protobuf.kotlin.DslList<ei.Ei.InventorySlot, InventorySlotsProxy>.set(index: kotlin.Int, value: ei.Ei.InventorySlot) {
      _builder.setInventorySlots(index, value)
    }
    /**
     * `repeated .ei.InventorySlot inventory_slots = 3;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearInventorySlots")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.InventorySlot, InventorySlotsProxy>.clear() {
      _builder.clearInventorySlots()
    }


    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ActiveArtifactsDEPRECATEDProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .ei.ArtifactsDB.ActiveArtifactSlot active_artifacts_DEPRECATED = 7;`
     */
     public val activeArtifactsDEPRECATED: com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.ActiveArtifactSlot, ActiveArtifactsDEPRECATEDProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.activeArtifactsDEPRECATEDList
      )
    /**
     * `repeated .ei.ArtifactsDB.ActiveArtifactSlot active_artifacts_DEPRECATED = 7;`
     * @param value The activeArtifactsDEPRECATED to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addActiveArtifactsDEPRECATED")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.ActiveArtifactSlot, ActiveArtifactsDEPRECATEDProxy>.add(value: ei.Ei.ArtifactsDB.ActiveArtifactSlot) {
      _builder.addActiveArtifactsDEPRECATED(value)
    }
    /**
     * `repeated .ei.ArtifactsDB.ActiveArtifactSlot active_artifacts_DEPRECATED = 7;`
     * @param value The activeArtifactsDEPRECATED to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignActiveArtifactsDEPRECATED")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.ActiveArtifactSlot, ActiveArtifactsDEPRECATEDProxy>.plusAssign(value: ei.Ei.ArtifactsDB.ActiveArtifactSlot) {
      add(value)
    }
    /**
     * `repeated .ei.ArtifactsDB.ActiveArtifactSlot active_artifacts_DEPRECATED = 7;`
     * @param values The activeArtifactsDEPRECATED to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllActiveArtifactsDEPRECATED")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.ActiveArtifactSlot, ActiveArtifactsDEPRECATEDProxy>.addAll(values: kotlin.collections.Iterable<ei.Ei.ArtifactsDB.ActiveArtifactSlot>) {
      _builder.addAllActiveArtifactsDEPRECATED(values)
    }
    /**
     * `repeated .ei.ArtifactsDB.ActiveArtifactSlot active_artifacts_DEPRECATED = 7;`
     * @param values The activeArtifactsDEPRECATED to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllActiveArtifactsDEPRECATED")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.ActiveArtifactSlot, ActiveArtifactsDEPRECATEDProxy>.plusAssign(values: kotlin.collections.Iterable<ei.Ei.ArtifactsDB.ActiveArtifactSlot>) {
      addAll(values)
    }
    /**
     * `repeated .ei.ArtifactsDB.ActiveArtifactSlot active_artifacts_DEPRECATED = 7;`
     * @param index The index to set the value at.
     * @param value The activeArtifactsDEPRECATED to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setActiveArtifactsDEPRECATED")
    public operator fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.ActiveArtifactSlot, ActiveArtifactsDEPRECATEDProxy>.set(index: kotlin.Int, value: ei.Ei.ArtifactsDB.ActiveArtifactSlot) {
      _builder.setActiveArtifactsDEPRECATED(index, value)
    }
    /**
     * `repeated .ei.ArtifactsDB.ActiveArtifactSlot active_artifacts_DEPRECATED = 7;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearActiveArtifactsDEPRECATED")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.ActiveArtifactSlot, ActiveArtifactsDEPRECATEDProxy>.clear() {
      _builder.clearActiveArtifactsDEPRECATED()
    }


    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ActiveArtifactSetsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .ei.ArtifactsDB.ActiveArtifactSet active_artifact_sets = 11;`
     */
     public val activeArtifactSets: com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.ActiveArtifactSet, ActiveArtifactSetsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.activeArtifactSetsList
      )
    /**
     * `repeated .ei.ArtifactsDB.ActiveArtifactSet active_artifact_sets = 11;`
     * @param value The activeArtifactSets to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addActiveArtifactSets")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.ActiveArtifactSet, ActiveArtifactSetsProxy>.add(value: ei.Ei.ArtifactsDB.ActiveArtifactSet) {
      _builder.addActiveArtifactSets(value)
    }
    /**
     * `repeated .ei.ArtifactsDB.ActiveArtifactSet active_artifact_sets = 11;`
     * @param value The activeArtifactSets to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignActiveArtifactSets")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.ActiveArtifactSet, ActiveArtifactSetsProxy>.plusAssign(value: ei.Ei.ArtifactsDB.ActiveArtifactSet) {
      add(value)
    }
    /**
     * `repeated .ei.ArtifactsDB.ActiveArtifactSet active_artifact_sets = 11;`
     * @param values The activeArtifactSets to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllActiveArtifactSets")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.ActiveArtifactSet, ActiveArtifactSetsProxy>.addAll(values: kotlin.collections.Iterable<ei.Ei.ArtifactsDB.ActiveArtifactSet>) {
      _builder.addAllActiveArtifactSets(values)
    }
    /**
     * `repeated .ei.ArtifactsDB.ActiveArtifactSet active_artifact_sets = 11;`
     * @param values The activeArtifactSets to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllActiveArtifactSets")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.ActiveArtifactSet, ActiveArtifactSetsProxy>.plusAssign(values: kotlin.collections.Iterable<ei.Ei.ArtifactsDB.ActiveArtifactSet>) {
      addAll(values)
    }
    /**
     * `repeated .ei.ArtifactsDB.ActiveArtifactSet active_artifact_sets = 11;`
     * @param index The index to set the value at.
     * @param value The activeArtifactSets to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setActiveArtifactSets")
    public operator fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.ActiveArtifactSet, ActiveArtifactSetsProxy>.set(index: kotlin.Int, value: ei.Ei.ArtifactsDB.ActiveArtifactSet) {
      _builder.setActiveArtifactSets(index, value)
    }
    /**
     * `repeated .ei.ArtifactsDB.ActiveArtifactSet active_artifact_sets = 11;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearActiveArtifactSets")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.ActiveArtifactSet, ActiveArtifactSetsProxy>.clear() {
      _builder.clearActiveArtifactSets()
    }


    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class SavedArtifactSetsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .ei.ArtifactsDB.ActiveArtifactSet saved_artifact_sets = 13;`
     */
     public val savedArtifactSets: com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.ActiveArtifactSet, SavedArtifactSetsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.savedArtifactSetsList
      )
    /**
     * `repeated .ei.ArtifactsDB.ActiveArtifactSet saved_artifact_sets = 13;`
     * @param value The savedArtifactSets to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addSavedArtifactSets")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.ActiveArtifactSet, SavedArtifactSetsProxy>.add(value: ei.Ei.ArtifactsDB.ActiveArtifactSet) {
      _builder.addSavedArtifactSets(value)
    }
    /**
     * `repeated .ei.ArtifactsDB.ActiveArtifactSet saved_artifact_sets = 13;`
     * @param value The savedArtifactSets to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignSavedArtifactSets")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.ActiveArtifactSet, SavedArtifactSetsProxy>.plusAssign(value: ei.Ei.ArtifactsDB.ActiveArtifactSet) {
      add(value)
    }
    /**
     * `repeated .ei.ArtifactsDB.ActiveArtifactSet saved_artifact_sets = 13;`
     * @param values The savedArtifactSets to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllSavedArtifactSets")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.ActiveArtifactSet, SavedArtifactSetsProxy>.addAll(values: kotlin.collections.Iterable<ei.Ei.ArtifactsDB.ActiveArtifactSet>) {
      _builder.addAllSavedArtifactSets(values)
    }
    /**
     * `repeated .ei.ArtifactsDB.ActiveArtifactSet saved_artifact_sets = 13;`
     * @param values The savedArtifactSets to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllSavedArtifactSets")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.ActiveArtifactSet, SavedArtifactSetsProxy>.plusAssign(values: kotlin.collections.Iterable<ei.Ei.ArtifactsDB.ActiveArtifactSet>) {
      addAll(values)
    }
    /**
     * `repeated .ei.ArtifactsDB.ActiveArtifactSet saved_artifact_sets = 13;`
     * @param index The index to set the value at.
     * @param value The savedArtifactSets to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setSavedArtifactSets")
    public operator fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.ActiveArtifactSet, SavedArtifactSetsProxy>.set(index: kotlin.Int, value: ei.Ei.ArtifactsDB.ActiveArtifactSet) {
      _builder.setSavedArtifactSets(index, value)
    }
    /**
     * `repeated .ei.ArtifactsDB.ActiveArtifactSet saved_artifact_sets = 13;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearSavedArtifactSets")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.ActiveArtifactSet, SavedArtifactSetsProxy>.clear() {
      _builder.clearSavedArtifactSets()
    }


    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ArtifactStatusProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .ei.ArtifactsDB.CraftableArtifact artifact_status = 12;`
     */
     public val artifactStatus: com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.CraftableArtifact, ArtifactStatusProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.artifactStatusList
      )
    /**
     * `repeated .ei.ArtifactsDB.CraftableArtifact artifact_status = 12;`
     * @param value The artifactStatus to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addArtifactStatus")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.CraftableArtifact, ArtifactStatusProxy>.add(value: ei.Ei.ArtifactsDB.CraftableArtifact) {
      _builder.addArtifactStatus(value)
    }
    /**
     * `repeated .ei.ArtifactsDB.CraftableArtifact artifact_status = 12;`
     * @param value The artifactStatus to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignArtifactStatus")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.CraftableArtifact, ArtifactStatusProxy>.plusAssign(value: ei.Ei.ArtifactsDB.CraftableArtifact) {
      add(value)
    }
    /**
     * `repeated .ei.ArtifactsDB.CraftableArtifact artifact_status = 12;`
     * @param values The artifactStatus to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllArtifactStatus")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.CraftableArtifact, ArtifactStatusProxy>.addAll(values: kotlin.collections.Iterable<ei.Ei.ArtifactsDB.CraftableArtifact>) {
      _builder.addAllArtifactStatus(values)
    }
    /**
     * `repeated .ei.ArtifactsDB.CraftableArtifact artifact_status = 12;`
     * @param values The artifactStatus to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllArtifactStatus")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.CraftableArtifact, ArtifactStatusProxy>.plusAssign(values: kotlin.collections.Iterable<ei.Ei.ArtifactsDB.CraftableArtifact>) {
      addAll(values)
    }
    /**
     * `repeated .ei.ArtifactsDB.CraftableArtifact artifact_status = 12;`
     * @param index The index to set the value at.
     * @param value The artifactStatus to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setArtifactStatus")
    public operator fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.CraftableArtifact, ArtifactStatusProxy>.set(index: kotlin.Int, value: ei.Ei.ArtifactsDB.CraftableArtifact) {
      _builder.setArtifactStatus(index, value)
    }
    /**
     * `repeated .ei.ArtifactsDB.CraftableArtifact artifact_status = 12;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearArtifactStatus")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.CraftableArtifact, ArtifactStatusProxy>.clear() {
      _builder.clearArtifactStatus()
    }


    /**
     * `optional .ei.MissionInfo fueling_mission = 14;`
     */
    public var fuelingMission: ei.Ei.MissionInfo
      @JvmName("getFuelingMission")
      get() = _builder.fuelingMission
      @JvmName("setFuelingMission")
      set(value) {
        _builder.fuelingMission = value
      }
    /**
     * `optional .ei.MissionInfo fueling_mission = 14;`
     */
    public fun clearFuelingMission() {
      _builder.clearFuelingMission()
    }
    /**
     * `optional .ei.MissionInfo fueling_mission = 14;`
     * @return Whether the fuelingMission field is set.
     */
    public fun hasFuelingMission(): kotlin.Boolean {
      return _builder.hasFuelingMission()
    }

    public val ArtifactsDBKt.Dsl.fuelingMissionOrNull: ei.Ei.MissionInfo?
      get() = _builder.fuelingMissionOrNull

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class MissionInfosProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .ei.MissionInfo mission_infos = 4;`
     */
     public val missionInfos: com.google.protobuf.kotlin.DslList<ei.Ei.MissionInfo, MissionInfosProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.missionInfosList
      )
    /**
     * `repeated .ei.MissionInfo mission_infos = 4;`
     * @param value The missionInfos to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addMissionInfos")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.MissionInfo, MissionInfosProxy>.add(value: ei.Ei.MissionInfo) {
      _builder.addMissionInfos(value)
    }
    /**
     * `repeated .ei.MissionInfo mission_infos = 4;`
     * @param value The missionInfos to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignMissionInfos")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ei.Ei.MissionInfo, MissionInfosProxy>.plusAssign(value: ei.Ei.MissionInfo) {
      add(value)
    }
    /**
     * `repeated .ei.MissionInfo mission_infos = 4;`
     * @param values The missionInfos to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllMissionInfos")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.MissionInfo, MissionInfosProxy>.addAll(values: kotlin.collections.Iterable<ei.Ei.MissionInfo>) {
      _builder.addAllMissionInfos(values)
    }
    /**
     * `repeated .ei.MissionInfo mission_infos = 4;`
     * @param values The missionInfos to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllMissionInfos")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ei.Ei.MissionInfo, MissionInfosProxy>.plusAssign(values: kotlin.collections.Iterable<ei.Ei.MissionInfo>) {
      addAll(values)
    }
    /**
     * `repeated .ei.MissionInfo mission_infos = 4;`
     * @param index The index to set the value at.
     * @param value The missionInfos to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setMissionInfos")
    public operator fun com.google.protobuf.kotlin.DslList<ei.Ei.MissionInfo, MissionInfosProxy>.set(index: kotlin.Int, value: ei.Ei.MissionInfo) {
      _builder.setMissionInfos(index, value)
    }
    /**
     * `repeated .ei.MissionInfo mission_infos = 4;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearMissionInfos")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.MissionInfo, MissionInfosProxy>.clear() {
      _builder.clearMissionInfos()
    }


    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class MissionArchiveProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .ei.MissionInfo mission_archive = 5;`
     */
     public val missionArchive: com.google.protobuf.kotlin.DslList<ei.Ei.MissionInfo, MissionArchiveProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.missionArchiveList
      )
    /**
     * `repeated .ei.MissionInfo mission_archive = 5;`
     * @param value The missionArchive to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addMissionArchive")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.MissionInfo, MissionArchiveProxy>.add(value: ei.Ei.MissionInfo) {
      _builder.addMissionArchive(value)
    }
    /**
     * `repeated .ei.MissionInfo mission_archive = 5;`
     * @param value The missionArchive to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignMissionArchive")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ei.Ei.MissionInfo, MissionArchiveProxy>.plusAssign(value: ei.Ei.MissionInfo) {
      add(value)
    }
    /**
     * `repeated .ei.MissionInfo mission_archive = 5;`
     * @param values The missionArchive to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllMissionArchive")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.MissionInfo, MissionArchiveProxy>.addAll(values: kotlin.collections.Iterable<ei.Ei.MissionInfo>) {
      _builder.addAllMissionArchive(values)
    }
    /**
     * `repeated .ei.MissionInfo mission_archive = 5;`
     * @param values The missionArchive to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllMissionArchive")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ei.Ei.MissionInfo, MissionArchiveProxy>.plusAssign(values: kotlin.collections.Iterable<ei.Ei.MissionInfo>) {
      addAll(values)
    }
    /**
     * `repeated .ei.MissionInfo mission_archive = 5;`
     * @param index The index to set the value at.
     * @param value The missionArchive to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setMissionArchive")
    public operator fun com.google.protobuf.kotlin.DslList<ei.Ei.MissionInfo, MissionArchiveProxy>.set(index: kotlin.Int, value: ei.Ei.MissionInfo) {
      _builder.setMissionArchive(index, value)
    }
    /**
     * `repeated .ei.MissionInfo mission_archive = 5;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearMissionArchive")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.MissionInfo, MissionArchiveProxy>.clear() {
      _builder.clearMissionArchive()
    }


    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class DiscoveredArtifactsDEPRECATEDProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .ei.ArtifactSpec discovered_artifacts_DEPRECATED = 8;`
     */
     public val discoveredArtifactsDEPRECATED: com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactSpec, DiscoveredArtifactsDEPRECATEDProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.discoveredArtifactsDEPRECATEDList
      )
    /**
     * `repeated .ei.ArtifactSpec discovered_artifacts_DEPRECATED = 8;`
     * @param value The discoveredArtifactsDEPRECATED to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addDiscoveredArtifactsDEPRECATED")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactSpec, DiscoveredArtifactsDEPRECATEDProxy>.add(value: ei.Ei.ArtifactSpec) {
      _builder.addDiscoveredArtifactsDEPRECATED(value)
    }
    /**
     * `repeated .ei.ArtifactSpec discovered_artifacts_DEPRECATED = 8;`
     * @param value The discoveredArtifactsDEPRECATED to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignDiscoveredArtifactsDEPRECATED")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactSpec, DiscoveredArtifactsDEPRECATEDProxy>.plusAssign(value: ei.Ei.ArtifactSpec) {
      add(value)
    }
    /**
     * `repeated .ei.ArtifactSpec discovered_artifacts_DEPRECATED = 8;`
     * @param values The discoveredArtifactsDEPRECATED to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllDiscoveredArtifactsDEPRECATED")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactSpec, DiscoveredArtifactsDEPRECATEDProxy>.addAll(values: kotlin.collections.Iterable<ei.Ei.ArtifactSpec>) {
      _builder.addAllDiscoveredArtifactsDEPRECATED(values)
    }
    /**
     * `repeated .ei.ArtifactSpec discovered_artifacts_DEPRECATED = 8;`
     * @param values The discoveredArtifactsDEPRECATED to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllDiscoveredArtifactsDEPRECATED")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactSpec, DiscoveredArtifactsDEPRECATEDProxy>.plusAssign(values: kotlin.collections.Iterable<ei.Ei.ArtifactSpec>) {
      addAll(values)
    }
    /**
     * `repeated .ei.ArtifactSpec discovered_artifacts_DEPRECATED = 8;`
     * @param index The index to set the value at.
     * @param value The discoveredArtifactsDEPRECATED to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setDiscoveredArtifactsDEPRECATED")
    public operator fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactSpec, DiscoveredArtifactsDEPRECATEDProxy>.set(index: kotlin.Int, value: ei.Ei.ArtifactSpec) {
      _builder.setDiscoveredArtifactsDEPRECATED(index, value)
    }
    /**
     * `repeated .ei.ArtifactSpec discovered_artifacts_DEPRECATED = 8;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearDiscoveredArtifactsDEPRECATED")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactSpec, DiscoveredArtifactsDEPRECATEDProxy>.clear() {
      _builder.clearDiscoveredArtifactsDEPRECATED()
    }


    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class CraftableArtifactsDEPRECATEDProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .ei.ArtifactsDB.CraftableArtifact craftable_artifacts_DEPRECATED = 9;`
     */
     public val craftableArtifactsDEPRECATED: com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.CraftableArtifact, CraftableArtifactsDEPRECATEDProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.craftableArtifactsDEPRECATEDList
      )
    /**
     * `repeated .ei.ArtifactsDB.CraftableArtifact craftable_artifacts_DEPRECATED = 9;`
     * @param value The craftableArtifactsDEPRECATED to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addCraftableArtifactsDEPRECATED")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.CraftableArtifact, CraftableArtifactsDEPRECATEDProxy>.add(value: ei.Ei.ArtifactsDB.CraftableArtifact) {
      _builder.addCraftableArtifactsDEPRECATED(value)
    }
    /**
     * `repeated .ei.ArtifactsDB.CraftableArtifact craftable_artifacts_DEPRECATED = 9;`
     * @param value The craftableArtifactsDEPRECATED to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignCraftableArtifactsDEPRECATED")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.CraftableArtifact, CraftableArtifactsDEPRECATEDProxy>.plusAssign(value: ei.Ei.ArtifactsDB.CraftableArtifact) {
      add(value)
    }
    /**
     * `repeated .ei.ArtifactsDB.CraftableArtifact craftable_artifacts_DEPRECATED = 9;`
     * @param values The craftableArtifactsDEPRECATED to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllCraftableArtifactsDEPRECATED")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.CraftableArtifact, CraftableArtifactsDEPRECATEDProxy>.addAll(values: kotlin.collections.Iterable<ei.Ei.ArtifactsDB.CraftableArtifact>) {
      _builder.addAllCraftableArtifactsDEPRECATED(values)
    }
    /**
     * `repeated .ei.ArtifactsDB.CraftableArtifact craftable_artifacts_DEPRECATED = 9;`
     * @param values The craftableArtifactsDEPRECATED to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllCraftableArtifactsDEPRECATED")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.CraftableArtifact, CraftableArtifactsDEPRECATEDProxy>.plusAssign(values: kotlin.collections.Iterable<ei.Ei.ArtifactsDB.CraftableArtifact>) {
      addAll(values)
    }
    /**
     * `repeated .ei.ArtifactsDB.CraftableArtifact craftable_artifacts_DEPRECATED = 9;`
     * @param index The index to set the value at.
     * @param value The craftableArtifactsDEPRECATED to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setCraftableArtifactsDEPRECATED")
    public operator fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.CraftableArtifact, CraftableArtifactsDEPRECATEDProxy>.set(index: kotlin.Int, value: ei.Ei.ArtifactsDB.CraftableArtifact) {
      _builder.setCraftableArtifactsDEPRECATED(index, value)
    }
    /**
     * `repeated .ei.ArtifactsDB.CraftableArtifact craftable_artifacts_DEPRECATED = 9;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearCraftableArtifactsDEPRECATED")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.CraftableArtifact, CraftableArtifactsDEPRECATEDProxy>.clear() {
      _builder.clearCraftableArtifactsDEPRECATED()
    }


    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class CraftingCountsDEPRECATEDProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .ei.ArtifactsDB.CraftableArtifact crafting_counts_DEPRECATED = 10;`
     */
     public val craftingCountsDEPRECATED: com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.CraftableArtifact, CraftingCountsDEPRECATEDProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.craftingCountsDEPRECATEDList
      )
    /**
     * `repeated .ei.ArtifactsDB.CraftableArtifact crafting_counts_DEPRECATED = 10;`
     * @param value The craftingCountsDEPRECATED to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addCraftingCountsDEPRECATED")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.CraftableArtifact, CraftingCountsDEPRECATEDProxy>.add(value: ei.Ei.ArtifactsDB.CraftableArtifact) {
      _builder.addCraftingCountsDEPRECATED(value)
    }
    /**
     * `repeated .ei.ArtifactsDB.CraftableArtifact crafting_counts_DEPRECATED = 10;`
     * @param value The craftingCountsDEPRECATED to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignCraftingCountsDEPRECATED")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.CraftableArtifact, CraftingCountsDEPRECATEDProxy>.plusAssign(value: ei.Ei.ArtifactsDB.CraftableArtifact) {
      add(value)
    }
    /**
     * `repeated .ei.ArtifactsDB.CraftableArtifact crafting_counts_DEPRECATED = 10;`
     * @param values The craftingCountsDEPRECATED to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllCraftingCountsDEPRECATED")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.CraftableArtifact, CraftingCountsDEPRECATEDProxy>.addAll(values: kotlin.collections.Iterable<ei.Ei.ArtifactsDB.CraftableArtifact>) {
      _builder.addAllCraftingCountsDEPRECATED(values)
    }
    /**
     * `repeated .ei.ArtifactsDB.CraftableArtifact crafting_counts_DEPRECATED = 10;`
     * @param values The craftingCountsDEPRECATED to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllCraftingCountsDEPRECATED")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.CraftableArtifact, CraftingCountsDEPRECATEDProxy>.plusAssign(values: kotlin.collections.Iterable<ei.Ei.ArtifactsDB.CraftableArtifact>) {
      addAll(values)
    }
    /**
     * `repeated .ei.ArtifactsDB.CraftableArtifact crafting_counts_DEPRECATED = 10;`
     * @param index The index to set the value at.
     * @param value The craftingCountsDEPRECATED to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setCraftingCountsDEPRECATED")
    public operator fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.CraftableArtifact, CraftingCountsDEPRECATEDProxy>.set(index: kotlin.Int, value: ei.Ei.ArtifactsDB.CraftableArtifact) {
      _builder.setCraftingCountsDEPRECATED(index, value)
    }
    /**
     * `repeated .ei.ArtifactsDB.CraftableArtifact crafting_counts_DEPRECATED = 10;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearCraftingCountsDEPRECATED")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.CraftableArtifact, CraftingCountsDEPRECATEDProxy>.clear() {
      _builder.clearCraftingCountsDEPRECATED()
    }

  }
  @kotlin.jvm.JvmName("-initializeactiveArtifactSlot")
  public inline fun activeArtifactSlot(block: ei.ArtifactsDBKt.ActiveArtifactSlotKt.Dsl.() -> kotlin.Unit): ei.Ei.ArtifactsDB.ActiveArtifactSlot =
    ei.ArtifactsDBKt.ActiveArtifactSlotKt.Dsl._create(ei.Ei.ArtifactsDB.ActiveArtifactSlot.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `ei.ArtifactsDB.ActiveArtifactSlot`
   */
  public object ActiveArtifactSlotKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: ei.Ei.ArtifactsDB.ActiveArtifactSlot.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: ei.Ei.ArtifactsDB.ActiveArtifactSlot.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): ei.Ei.ArtifactsDB.ActiveArtifactSlot = _builder.build()

      /**
       * `optional bool occupied = 1;`
       */
      public var occupied: kotlin.Boolean
        @JvmName("getOccupied")
        get() = _builder.occupied
        @JvmName("setOccupied")
        set(value) {
          _builder.occupied = value
        }
      /**
       * `optional bool occupied = 1;`
       */
      public fun clearOccupied() {
        _builder.clearOccupied()
      }
      /**
       * `optional bool occupied = 1;`
       * @return Whether the occupied field is set.
       */
      public fun hasOccupied(): kotlin.Boolean {
        return _builder.hasOccupied()
      }

      /**
       * `optional uint64 item_id = 2;`
       */
      public var itemId: kotlin.Long
        @JvmName("getItemId")
        get() = _builder.itemId
        @JvmName("setItemId")
        set(value) {
          _builder.itemId = value
        }
      /**
       * `optional uint64 item_id = 2;`
       */
      public fun clearItemId() {
        _builder.clearItemId()
      }
      /**
       * `optional uint64 item_id = 2;`
       * @return Whether the itemId field is set.
       */
      public fun hasItemId(): kotlin.Boolean {
        return _builder.hasItemId()
      }
    }
  }
  @kotlin.jvm.JvmName("-initializeactiveArtifactSet")
  public inline fun activeArtifactSet(block: ei.ArtifactsDBKt.ActiveArtifactSetKt.Dsl.() -> kotlin.Unit): ei.Ei.ArtifactsDB.ActiveArtifactSet =
    ei.ArtifactsDBKt.ActiveArtifactSetKt.Dsl._create(ei.Ei.ArtifactsDB.ActiveArtifactSet.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `ei.ArtifactsDB.ActiveArtifactSet`
   */
  public object ActiveArtifactSetKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: ei.Ei.ArtifactsDB.ActiveArtifactSet.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: ei.Ei.ArtifactsDB.ActiveArtifactSet.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): ei.Ei.ArtifactsDB.ActiveArtifactSet = _builder.build()

      /**
       * An uninstantiable, behaviorless type to represent the field in
       * generics.
       */
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      public class SlotsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
      /**
       * `repeated .ei.ArtifactsDB.ActiveArtifactSlot slots = 1;`
       */
       public val slots: com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.ActiveArtifactSlot, SlotsProxy>
        @kotlin.jvm.JvmSynthetic
        get() = com.google.protobuf.kotlin.DslList(
          _builder.slotsList
        )
      /**
       * `repeated .ei.ArtifactsDB.ActiveArtifactSlot slots = 1;`
       * @param value The slots to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("addSlots")
      public fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.ActiveArtifactSlot, SlotsProxy>.add(value: ei.Ei.ArtifactsDB.ActiveArtifactSlot) {
        _builder.addSlots(value)
      }
      /**
       * `repeated .ei.ArtifactsDB.ActiveArtifactSlot slots = 1;`
       * @param value The slots to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("plusAssignSlots")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.ActiveArtifactSlot, SlotsProxy>.plusAssign(value: ei.Ei.ArtifactsDB.ActiveArtifactSlot) {
        add(value)
      }
      /**
       * `repeated .ei.ArtifactsDB.ActiveArtifactSlot slots = 1;`
       * @param values The slots to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("addAllSlots")
      public fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.ActiveArtifactSlot, SlotsProxy>.addAll(values: kotlin.collections.Iterable<ei.Ei.ArtifactsDB.ActiveArtifactSlot>) {
        _builder.addAllSlots(values)
      }
      /**
       * `repeated .ei.ArtifactsDB.ActiveArtifactSlot slots = 1;`
       * @param values The slots to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("plusAssignAllSlots")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.ActiveArtifactSlot, SlotsProxy>.plusAssign(values: kotlin.collections.Iterable<ei.Ei.ArtifactsDB.ActiveArtifactSlot>) {
        addAll(values)
      }
      /**
       * `repeated .ei.ArtifactsDB.ActiveArtifactSlot slots = 1;`
       * @param index The index to set the value at.
       * @param value The slots to set.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("setSlots")
      public operator fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.ActiveArtifactSlot, SlotsProxy>.set(index: kotlin.Int, value: ei.Ei.ArtifactsDB.ActiveArtifactSlot) {
        _builder.setSlots(index, value)
      }
      /**
       * `repeated .ei.ArtifactsDB.ActiveArtifactSlot slots = 1;`
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("clearSlots")
      public fun com.google.protobuf.kotlin.DslList<ei.Ei.ArtifactsDB.ActiveArtifactSlot, SlotsProxy>.clear() {
        _builder.clearSlots()
      }


      /**
       * `optional uint32 uid = 2;`
       */
      public var uid: kotlin.Int
        @JvmName("getUid")
        get() = _builder.uid
        @JvmName("setUid")
        set(value) {
          _builder.uid = value
        }
      /**
       * `optional uint32 uid = 2;`
       */
      public fun clearUid() {
        _builder.clearUid()
      }
      /**
       * `optional uint32 uid = 2;`
       * @return Whether the uid field is set.
       */
      public fun hasUid(): kotlin.Boolean {
        return _builder.hasUid()
      }
    }
  }
  @kotlin.jvm.JvmName("-initializecraftableArtifact")
  public inline fun craftableArtifact(block: ei.ArtifactsDBKt.CraftableArtifactKt.Dsl.() -> kotlin.Unit): ei.Ei.ArtifactsDB.CraftableArtifact =
    ei.ArtifactsDBKt.CraftableArtifactKt.Dsl._create(ei.Ei.ArtifactsDB.CraftableArtifact.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `ei.ArtifactsDB.CraftableArtifact`
   */
  public object CraftableArtifactKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: ei.Ei.ArtifactsDB.CraftableArtifact.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: ei.Ei.ArtifactsDB.CraftableArtifact.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): ei.Ei.ArtifactsDB.CraftableArtifact = _builder.build()

      /**
       * `optional .ei.ArtifactSpec spec = 1;`
       */
      public var spec: ei.Ei.ArtifactSpec
        @JvmName("getSpec")
        get() = _builder.spec
        @JvmName("setSpec")
        set(value) {
          _builder.spec = value
        }
      /**
       * `optional .ei.ArtifactSpec spec = 1;`
       */
      public fun clearSpec() {
        _builder.clearSpec()
      }
      /**
       * `optional .ei.ArtifactSpec spec = 1;`
       * @return Whether the spec field is set.
       */
      public fun hasSpec(): kotlin.Boolean {
        return _builder.hasSpec()
      }

      public val CraftableArtifactKt.Dsl.specOrNull: ei.Ei.ArtifactSpec?
        get() = _builder.specOrNull

      /**
       * `optional bool discovered = 6;`
       */
      public var discovered: kotlin.Boolean
        @JvmName("getDiscovered")
        get() = _builder.discovered
        @JvmName("setDiscovered")
        set(value) {
          _builder.discovered = value
        }
      /**
       * `optional bool discovered = 6;`
       */
      public fun clearDiscovered() {
        _builder.clearDiscovered()
      }
      /**
       * `optional bool discovered = 6;`
       * @return Whether the discovered field is set.
       */
      public fun hasDiscovered(): kotlin.Boolean {
        return _builder.hasDiscovered()
      }

      /**
       * `optional bool craftable = 4;`
       */
      public var craftable: kotlin.Boolean
        @JvmName("getCraftable")
        get() = _builder.craftable
        @JvmName("setCraftable")
        set(value) {
          _builder.craftable = value
        }
      /**
       * `optional bool craftable = 4;`
       */
      public fun clearCraftable() {
        _builder.clearCraftable()
      }
      /**
       * `optional bool craftable = 4;`
       * @return Whether the craftable field is set.
       */
      public fun hasCraftable(): kotlin.Boolean {
        return _builder.hasCraftable()
      }

      /**
       * `optional bool recipe_discovered = 5;`
       */
      public var recipeDiscovered: kotlin.Boolean
        @JvmName("getRecipeDiscovered")
        get() = _builder.recipeDiscovered
        @JvmName("setRecipeDiscovered")
        set(value) {
          _builder.recipeDiscovered = value
        }
      /**
       * `optional bool recipe_discovered = 5;`
       */
      public fun clearRecipeDiscovered() {
        _builder.clearRecipeDiscovered()
      }
      /**
       * `optional bool recipe_discovered = 5;`
       * @return Whether the recipeDiscovered field is set.
       */
      public fun hasRecipeDiscovered(): kotlin.Boolean {
        return _builder.hasRecipeDiscovered()
      }

      /**
       * `optional bool seen = 2;`
       */
      public var seen: kotlin.Boolean
        @JvmName("getSeen")
        get() = _builder.seen
        @JvmName("setSeen")
        set(value) {
          _builder.seen = value
        }
      /**
       * `optional bool seen = 2;`
       */
      public fun clearSeen() {
        _builder.clearSeen()
      }
      /**
       * `optional bool seen = 2;`
       * @return Whether the seen field is set.
       */
      public fun hasSeen(): kotlin.Boolean {
        return _builder.hasSeen()
      }

      /**
       * `optional uint32 count = 3;`
       */
      public var count: kotlin.Int
        @JvmName("getCount")
        get() = _builder.count
        @JvmName("setCount")
        set(value) {
          _builder.count = value
        }
      /**
       * `optional uint32 count = 3;`
       */
      public fun clearCount() {
        _builder.clearCount()
      }
      /**
       * `optional uint32 count = 3;`
       * @return Whether the count field is set.
       */
      public fun hasCount(): kotlin.Boolean {
        return _builder.hasCount()
      }
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ei.Ei.ArtifactsDB.copy(block: `ei`.ArtifactsDBKt.Dsl.() -> kotlin.Unit): ei.Ei.ArtifactsDB =
  `ei`.ArtifactsDBKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun ei.Ei.ArtifactsDB.ActiveArtifactSlot.copy(block: `ei`.ArtifactsDBKt.ActiveArtifactSlotKt.Dsl.() -> kotlin.Unit): ei.Ei.ArtifactsDB.ActiveArtifactSlot =
  `ei`.ArtifactsDBKt.ActiveArtifactSlotKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun ei.Ei.ArtifactsDB.ActiveArtifactSet.copy(block: `ei`.ArtifactsDBKt.ActiveArtifactSetKt.Dsl.() -> kotlin.Unit): ei.Ei.ArtifactsDB.ActiveArtifactSet =
  `ei`.ArtifactsDBKt.ActiveArtifactSetKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun ei.Ei.ArtifactsDB.CraftableArtifact.copy(block: `ei`.ArtifactsDBKt.CraftableArtifactKt.Dsl.() -> kotlin.Unit): ei.Ei.ArtifactsDB.CraftableArtifact =
  `ei`.ArtifactsDBKt.CraftableArtifactKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val ei.Ei.ArtifactsDB.CraftableArtifactOrBuilder.specOrNull: ei.Ei.ArtifactSpec?
  get() = if (hasSpec()) getSpec() else null

public val ei.Ei.ArtifactsDBOrBuilder.fuelingMissionOrNull: ei.Ei.MissionInfo?
  get() = if (hasFuelingMission()) getFuelingMission() else null

