// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ei.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ei;

@kotlin.jvm.JvmName("-initializeclearAllUserDataRequest")
public inline fun clearAllUserDataRequest(block: ei.ClearAllUserDataRequestKt.Dsl.() -> kotlin.Unit): ei.Ei.ClearAllUserDataRequest =
  ei.ClearAllUserDataRequestKt.Dsl._create(ei.Ei.ClearAllUserDataRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ei.ClearAllUserDataRequest`
 */
public object ClearAllUserDataRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ei.Ei.ClearAllUserDataRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ei.Ei.ClearAllUserDataRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ei.Ei.ClearAllUserDataRequest = _builder.build()

    /**
     * `optional .ei.BasicRequestInfo rinfo = 4;`
     */
    public var rinfo: ei.Ei.BasicRequestInfo
      @JvmName("getRinfo")
      get() = _builder.rinfo
      @JvmName("setRinfo")
      set(value) {
        _builder.rinfo = value
      }
    /**
     * `optional .ei.BasicRequestInfo rinfo = 4;`
     */
    public fun clearRinfo() {
      _builder.clearRinfo()
    }
    /**
     * `optional .ei.BasicRequestInfo rinfo = 4;`
     * @return Whether the rinfo field is set.
     */
    public fun hasRinfo(): kotlin.Boolean {
      return _builder.hasRinfo()
    }
    public val ClearAllUserDataRequestKt.Dsl.rinfoOrNull: ei.Ei.BasicRequestInfo?
      get() = _builder.rinfoOrNull

    /**
     * `optional string user_id = 1;`
     */
    public var userId: kotlin.String
      @JvmName("getUserId")
      get() = _builder.userId
      @JvmName("setUserId")
      set(value) {
        _builder.userId = value
      }
    /**
     * `optional string user_id = 1;`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }
    /**
     * `optional string user_id = 1;`
     * @return Whether the userId field is set.
     */
    public fun hasUserId(): kotlin.Boolean {
      return _builder.hasUserId()
    }

    /**
     * `optional string device_id = 2;`
     */
    public var deviceId: kotlin.String
      @JvmName("getDeviceId")
      get() = _builder.deviceId
      @JvmName("setDeviceId")
      set(value) {
        _builder.deviceId = value
      }
    /**
     * `optional string device_id = 2;`
     */
    public fun clearDeviceId() {
      _builder.clearDeviceId()
    }
    /**
     * `optional string device_id = 2;`
     * @return Whether the deviceId field is set.
     */
    public fun hasDeviceId(): kotlin.Boolean {
      return _builder.hasDeviceId()
    }

    /**
     * `optional uint64 backup_checksum = 3;`
     */
    public var backupChecksum: kotlin.Long
      @JvmName("getBackupChecksum")
      get() = _builder.backupChecksum
      @JvmName("setBackupChecksum")
      set(value) {
        _builder.backupChecksum = value
      }
    /**
     * `optional uint64 backup_checksum = 3;`
     */
    public fun clearBackupChecksum() {
      _builder.clearBackupChecksum()
    }
    /**
     * `optional uint64 backup_checksum = 3;`
     * @return Whether the backupChecksum field is set.
     */
    public fun hasBackupChecksum(): kotlin.Boolean {
      return _builder.hasBackupChecksum()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ei.Ei.ClearAllUserDataRequest.copy(block: `ei`.ClearAllUserDataRequestKt.Dsl.() -> kotlin.Unit): ei.Ei.ClearAllUserDataRequest =
  `ei`.ClearAllUserDataRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val ei.Ei.ClearAllUserDataRequestOrBuilder.rinfoOrNull: ei.Ei.BasicRequestInfo?
  get() = if (hasRinfo()) getRinfo() else null

