// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ei.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ei;

@kotlin.jvm.JvmName("-initializecleanAccountRequest")
public inline fun cleanAccountRequest(block: ei.CleanAccountRequestKt.Dsl.() -> kotlin.Unit): ei.Ei.CleanAccountRequest =
  ei.CleanAccountRequestKt.Dsl._create(ei.Ei.CleanAccountRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ei.CleanAccountRequest`
 */
public object CleanAccountRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ei.Ei.CleanAccountRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: ei.Ei.CleanAccountRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): ei.Ei.CleanAccountRequest = _builder.build()

    /**
     * `optional string ei_user_id_to_keep = 1;`
     */
    public var eiUserIdToKeep: kotlin.String
      @kotlin.jvm.JvmName("getEiUserIdToKeep")
        get() = _builder.eiUserIdToKeep
      @kotlin.jvm.JvmName("setEiUserIdToKeep")
        set(value) {
        _builder.eiUserIdToKeep = value
      }
    /**
     * <code>optional string ei_user_id_to_keep = 1;</code>
     * @return This builder for chaining.
     */
    public fun clearEiUserIdToKeep() {
      _builder.clearEiUserIdToKeep()
    }
    /**
     * <code>optional string ei_user_id_to_keep = 1;</code>
     * @return Whether the eiUserIdToKeep field is set.
     * @return This builder for chaining.
     */
    public fun hasEiUserIdToKeep(): kotlin.Boolean {
      return _builder.hasEiUserIdToKeep()
    }

    /**
     * `optional string game_services_id = 2;`
     */
    public var gameServicesId: kotlin.String
      @kotlin.jvm.JvmName("getGameServicesId")
        get() = _builder.gameServicesId
      @kotlin.jvm.JvmName("setGameServicesId")
        set(value) {
        _builder.gameServicesId = value
      }
    /**
     * <code>optional string game_services_id = 2;</code>
     * @return This builder for chaining.
     */
    public fun clearGameServicesId() {
      _builder.clearGameServicesId()
    }
    /**
     * <code>optional string game_services_id = 2;</code>
     * @return Whether the gameServicesId field is set.
     * @return This builder for chaining.
     */
    public fun hasGameServicesId(): kotlin.Boolean {
      return _builder.hasGameServicesId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ei.Ei.CleanAccountRequest.copy(block: `ei`.CleanAccountRequestKt.Dsl.() -> kotlin.Unit): ei.Ei.CleanAccountRequest =
  `ei`.CleanAccountRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

