// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ei.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ei;

@kotlin.jvm.JvmName("-initializecontractAction")
public inline fun contractAction(block: ei.ContractActionKt.Dsl.() -> kotlin.Unit): ei.Ei.ContractAction =
  ei.ContractActionKt.Dsl._create(ei.Ei.ContractAction.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ei.ContractAction`
 */
public object ContractActionKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ei.Ei.ContractAction.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ei.Ei.ContractAction.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ei.Ei.ContractAction = _builder.build()

    /**
     * `optional string user_id = 1;`
     */
    public var userId: kotlin.String
      @JvmName("getUserId")
      get() = _builder.userId
      @JvmName("setUserId")
      set(value) {
        _builder.userId = value
      }
    /**
     * `optional string user_id = 1;`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }
    /**
     * `optional string user_id = 1;`
     * @return Whether the userId field is set.
     */
    public fun hasUserId(): kotlin.Boolean {
      return _builder.hasUserId()
    }

    /**
     * `optional string action_name = 2;`
     */
    public var actionName: kotlin.String
      @JvmName("getActionName")
      get() = _builder.actionName
      @JvmName("setActionName")
      set(value) {
        _builder.actionName = value
      }
    /**
     * `optional string action_name = 2;`
     */
    public fun clearActionName() {
      _builder.clearActionName()
    }
    /**
     * `optional string action_name = 2;`
     * @return Whether the actionName field is set.
     */
    public fun hasActionName(): kotlin.Boolean {
      return _builder.hasActionName()
    }

    /**
     * `optional double approx_time = 3;`
     */
    public var approxTime: kotlin.Double
      @JvmName("getApproxTime")
      get() = _builder.approxTime
      @JvmName("setApproxTime")
      set(value) {
        _builder.approxTime = value
      }
    /**
     * `optional double approx_time = 3;`
     */
    public fun clearApproxTime() {
      _builder.clearApproxTime()
    }
    /**
     * `optional double approx_time = 3;`
     * @return Whether the approxTime field is set.
     */
    public fun hasApproxTime(): kotlin.Boolean {
      return _builder.hasApproxTime()
    }

    /**
     * `optional string dest_user_id = 4;`
     */
    public var destUserId: kotlin.String
      @JvmName("getDestUserId")
      get() = _builder.destUserId
      @JvmName("setDestUserId")
      set(value) {
        _builder.destUserId = value
      }
    /**
     * `optional string dest_user_id = 4;`
     */
    public fun clearDestUserId() {
      _builder.clearDestUserId()
    }
    /**
     * `optional string dest_user_id = 4;`
     * @return Whether the destUserId field is set.
     */
    public fun hasDestUserId(): kotlin.Boolean {
      return _builder.hasDestUserId()
    }

    /**
     * `optional string contract_id = 5;`
     */
    public var contractId: kotlin.String
      @JvmName("getContractId")
      get() = _builder.contractId
      @JvmName("setContractId")
      set(value) {
        _builder.contractId = value
      }
    /**
     * `optional string contract_id = 5;`
     */
    public fun clearContractId() {
      _builder.clearContractId()
    }
    /**
     * `optional string contract_id = 5;`
     * @return Whether the contractId field is set.
     */
    public fun hasContractId(): kotlin.Boolean {
      return _builder.hasContractId()
    }

    /**
     * `optional string coop_id = 6;`
     */
    public var coopId: kotlin.String
      @JvmName("getCoopId")
      get() = _builder.coopId
      @JvmName("setCoopId")
      set(value) {
        _builder.coopId = value
      }
    /**
     * `optional string coop_id = 6;`
     */
    public fun clearCoopId() {
      _builder.clearCoopId()
    }
    /**
     * `optional string coop_id = 6;`
     * @return Whether the coopId field is set.
     */
    public fun hasCoopId(): kotlin.Boolean {
      return _builder.hasCoopId()
    }

    /**
     * `optional bool autojoin = 7;`
     */
    public var autojoin: kotlin.Boolean
      @JvmName("getAutojoin")
      get() = _builder.autojoin
      @JvmName("setAutojoin")
      set(value) {
        _builder.autojoin = value
      }
    /**
     * `optional bool autojoin = 7;`
     */
    public fun clearAutojoin() {
      _builder.clearAutojoin()
    }
    /**
     * `optional bool autojoin = 7;`
     * @return Whether the autojoin field is set.
     */
    public fun hasAutojoin(): kotlin.Boolean {
      return _builder.hasAutojoin()
    }

    /**
     * `optional uint32 grade = 8;`
     */
    public var grade: kotlin.Int
      @JvmName("getGrade")
      get() = _builder.grade
      @JvmName("setGrade")
      set(value) {
        _builder.grade = value
      }
    /**
     * `optional uint32 grade = 8;`
     */
    public fun clearGrade() {
      _builder.clearGrade()
    }
    /**
     * `optional uint32 grade = 8;`
     * @return Whether the grade field is set.
     */
    public fun hasGrade(): kotlin.Boolean {
      return _builder.hasGrade()
    }

    /**
     * `optional bool replay = 9;`
     */
    public var replay: kotlin.Boolean
      @JvmName("getReplay")
      get() = _builder.replay
      @JvmName("setReplay")
      set(value) {
        _builder.replay = value
      }
    /**
     * `optional bool replay = 9;`
     */
    public fun clearReplay() {
      _builder.clearReplay()
    }
    /**
     * `optional bool replay = 9;`
     * @return Whether the replay field is set.
     */
    public fun hasReplay(): kotlin.Boolean {
      return _builder.hasReplay()
    }

    /**
     * `optional bool points_replay = 10;`
     */
    public var pointsReplay: kotlin.Boolean
      @JvmName("getPointsReplay")
      get() = _builder.pointsReplay
      @JvmName("setPointsReplay")
      set(value) {
        _builder.pointsReplay = value
      }
    /**
     * `optional bool points_replay = 10;`
     */
    public fun clearPointsReplay() {
      _builder.clearPointsReplay()
    }
    /**
     * `optional bool points_replay = 10;`
     * @return Whether the pointsReplay field is set.
     */
    public fun hasPointsReplay(): kotlin.Boolean {
      return _builder.hasPointsReplay()
    }

    /**
     * `optional uint32 reward_type = 11;`
     */
    public var rewardType: kotlin.Int
      @JvmName("getRewardType")
      get() = _builder.rewardType
      @JvmName("setRewardType")
      set(value) {
        _builder.rewardType = value
      }
    /**
     * `optional uint32 reward_type = 11;`
     */
    public fun clearRewardType() {
      _builder.clearRewardType()
    }
    /**
     * `optional uint32 reward_type = 11;`
     * @return Whether the rewardType field is set.
     */
    public fun hasRewardType(): kotlin.Boolean {
      return _builder.hasRewardType()
    }

    /**
     * `optional string reward_subtype = 12;`
     */
    public var rewardSubtype: kotlin.String
      @JvmName("getRewardSubtype")
      get() = _builder.rewardSubtype
      @JvmName("setRewardSubtype")
      set(value) {
        _builder.rewardSubtype = value
      }
    /**
     * `optional string reward_subtype = 12;`
     */
    public fun clearRewardSubtype() {
      _builder.clearRewardSubtype()
    }
    /**
     * `optional string reward_subtype = 12;`
     * @return Whether the rewardSubtype field is set.
     */
    public fun hasRewardSubtype(): kotlin.Boolean {
      return _builder.hasRewardSubtype()
    }

    /**
     * `optional double reward_amount = 13;`
     */
    public var rewardAmount: kotlin.Double
      @JvmName("getRewardAmount")
      get() = _builder.rewardAmount
      @JvmName("setRewardAmount")
      set(value) {
        _builder.rewardAmount = value
      }
    /**
     * `optional double reward_amount = 13;`
     */
    public fun clearRewardAmount() {
      _builder.clearRewardAmount()
    }
    /**
     * `optional double reward_amount = 13;`
     * @return Whether the rewardAmount field is set.
     */
    public fun hasRewardAmount(): kotlin.Boolean {
      return _builder.hasRewardAmount()
    }

    /**
     * `optional uint32 goal_index = 14;`
     */
    public var goalIndex: kotlin.Int
      @JvmName("getGoalIndex")
      get() = _builder.goalIndex
      @JvmName("setGoalIndex")
      set(value) {
        _builder.goalIndex = value
      }
    /**
     * `optional uint32 goal_index = 14;`
     */
    public fun clearGoalIndex() {
      _builder.clearGoalIndex()
    }
    /**
     * `optional uint32 goal_index = 14;`
     * @return Whether the goalIndex field is set.
     */
    public fun hasGoalIndex(): kotlin.Boolean {
      return _builder.hasGoalIndex()
    }

    /**
     * `optional string boost_id = 15;`
     */
    public var boostId: kotlin.String
      @JvmName("getBoostId")
      get() = _builder.boostId
      @JvmName("setBoostId")
      set(value) {
        _builder.boostId = value
      }
    /**
     * `optional string boost_id = 15;`
     */
    public fun clearBoostId() {
      _builder.clearBoostId()
    }
    /**
     * `optional string boost_id = 15;`
     * @return Whether the boostId field is set.
     */
    public fun hasBoostId(): kotlin.Boolean {
      return _builder.hasBoostId()
    }

    /**
     * `optional uint32 tokens = 16;`
     */
    public var tokens: kotlin.Int
      @JvmName("getTokens")
      get() = _builder.tokens
      @JvmName("setTokens")
      set(value) {
        _builder.tokens = value
      }
    /**
     * `optional uint32 tokens = 16;`
     */
    public fun clearTokens() {
      _builder.clearTokens()
    }
    /**
     * `optional uint32 tokens = 16;`
     * @return Whether the tokens field is set.
     */
    public fun hasTokens(): kotlin.Boolean {
      return _builder.hasTokens()
    }

    /**
     * `optional uint32 kick_reason = 17;`
     */
    public var kickReason: kotlin.Int
      @JvmName("getKickReason")
      get() = _builder.kickReason
      @JvmName("setKickReason")
      set(value) {
        _builder.kickReason = value
      }
    /**
     * `optional uint32 kick_reason = 17;`
     */
    public fun clearKickReason() {
      _builder.clearKickReason()
    }
    /**
     * `optional uint32 kick_reason = 17;`
     * @return Whether the kickReason field is set.
     */
    public fun hasKickReason(): kotlin.Boolean {
      return _builder.hasKickReason()
    }

    /**
     * `optional bool public = 18;`
     */
    public var public: kotlin.Boolean
      @JvmName("getPublic")
      get() = _builder.public
      @JvmName("setPublic")
      set(value) {
        _builder.public = value
      }
    /**
     * `optional bool public = 18;`
     */
    public fun clearPublic() {
      _builder.clearPublic()
    }
    /**
     * `optional bool public = 18;`
     * @return Whether the public field is set.
     */
    public fun hasPublic(): kotlin.Boolean {
      return _builder.hasPublic()
    }

    /**
     * `optional bool cc_only = 19;`
     */
    public var ccOnly: kotlin.Boolean
      @JvmName("getCcOnly")
      get() = _builder.ccOnly
      @JvmName("setCcOnly")
      set(value) {
        _builder.ccOnly = value
      }
    /**
     * `optional bool cc_only = 19;`
     */
    public fun clearCcOnly() {
      _builder.clearCcOnly()
    }
    /**
     * `optional bool cc_only = 19;`
     * @return Whether the ccOnly field is set.
     */
    public fun hasCcOnly(): kotlin.Boolean {
      return _builder.hasCcOnly()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ei.Ei.ContractAction.copy(block: `ei`.ContractActionKt.Dsl.() -> kotlin.Unit): ei.Ei.ContractAction =
  `ei`.ContractActionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

