// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ei.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ei;

@kotlin.jvm.JvmName("-initializedLCItem")
public inline fun dLCItem(block: ei.DLCItemKt.Dsl.() -> kotlin.Unit): ei.Ei.DLCItem =
  ei.DLCItemKt.Dsl._create(ei.Ei.DLCItem.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ei.DLCItem`
 */
public object DLCItemKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ei.Ei.DLCItem.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ei.Ei.DLCItem.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ei.Ei.DLCItem = _builder.build()

    /**
     * `optional string name = 1;`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.name
      @JvmName("setName")
      set(value) {
        _builder.name = value
      }
    /**
     * `optional string name = 1;`
     */
    public fun clearName() {
      _builder.clearName()
    }
    /**
     * `optional string name = 1;`
     * @return Whether the name field is set.
     */
    public fun hasName(): kotlin.Boolean {
      return _builder.hasName()
    }

    /**
     * `optional string directory = 2;`
     */
    public var directory: kotlin.String
      @JvmName("getDirectory")
      get() = _builder.directory
      @JvmName("setDirectory")
      set(value) {
        _builder.directory = value
      }
    /**
     * `optional string directory = 2;`
     */
    public fun clearDirectory() {
      _builder.clearDirectory()
    }
    /**
     * `optional string directory = 2;`
     * @return Whether the directory field is set.
     */
    public fun hasDirectory(): kotlin.Boolean {
      return _builder.hasDirectory()
    }

    /**
     * `optional string ext = 3;`
     */
    public var ext: kotlin.String
      @JvmName("getExt")
      get() = _builder.ext
      @JvmName("setExt")
      set(value) {
        _builder.ext = value
      }
    /**
     * `optional string ext = 3;`
     */
    public fun clearExt() {
      _builder.clearExt()
    }
    /**
     * `optional string ext = 3;`
     * @return Whether the ext field is set.
     */
    public fun hasExt(): kotlin.Boolean {
      return _builder.hasExt()
    }

    /**
     * `optional bool compressed = 6;`
     */
    public var compressed: kotlin.Boolean
      @JvmName("getCompressed")
      get() = _builder.compressed
      @JvmName("setCompressed")
      set(value) {
        _builder.compressed = value
      }
    /**
     * `optional bool compressed = 6;`
     */
    public fun clearCompressed() {
      _builder.clearCompressed()
    }
    /**
     * `optional bool compressed = 6;`
     * @return Whether the compressed field is set.
     */
    public fun hasCompressed(): kotlin.Boolean {
      return _builder.hasCompressed()
    }

    /**
     * `optional uint64 original_size = 7;`
     */
    public var originalSize: kotlin.Long
      @JvmName("getOriginalSize")
      get() = _builder.originalSize
      @JvmName("setOriginalSize")
      set(value) {
        _builder.originalSize = value
      }
    /**
     * `optional uint64 original_size = 7;`
     */
    public fun clearOriginalSize() {
      _builder.clearOriginalSize()
    }
    /**
     * `optional uint64 original_size = 7;`
     * @return Whether the originalSize field is set.
     */
    public fun hasOriginalSize(): kotlin.Boolean {
      return _builder.hasOriginalSize()
    }

    /**
     * `optional string url = 4;`
     */
    public var url: kotlin.String
      @JvmName("getUrl")
      get() = _builder.url
      @JvmName("setUrl")
      set(value) {
        _builder.url = value
      }
    /**
     * `optional string url = 4;`
     */
    public fun clearUrl() {
      _builder.clearUrl()
    }
    /**
     * `optional string url = 4;`
     * @return Whether the url field is set.
     */
    public fun hasUrl(): kotlin.Boolean {
      return _builder.hasUrl()
    }

    /**
     * `optional string checksum = 5;`
     */
    public var checksum: kotlin.String
      @JvmName("getChecksum")
      get() = _builder.checksum
      @JvmName("setChecksum")
      set(value) {
        _builder.checksum = value
      }
    /**
     * `optional string checksum = 5;`
     */
    public fun clearChecksum() {
      _builder.clearChecksum()
    }
    /**
     * `optional string checksum = 5;`
     * @return Whether the checksum field is set.
     */
    public fun hasChecksum(): kotlin.Boolean {
      return _builder.hasChecksum()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ei.Ei.DLCItem.copy(block: `ei`.DLCItemKt.Dsl.() -> kotlin.Unit): ei.Ei.DLCItem =
  `ei`.DLCItemKt.Dsl._create(this.toBuilder()).apply { block() }._build()

