// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ei.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ei;

@kotlin.jvm.JvmName("-initializeeggIncEvent")
public inline fun eggIncEvent(block: ei.EggIncEventKt.Dsl.() -> kotlin.Unit): ei.Ei.EggIncEvent =
  ei.EggIncEventKt.Dsl._create(ei.Ei.EggIncEvent.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ei.EggIncEvent`
 */
public object EggIncEventKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ei.Ei.EggIncEvent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: ei.Ei.EggIncEvent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): ei.Ei.EggIncEvent = _builder.build()

    /**
     * `optional string identifier = 1;`
     */
    public var identifier: kotlin.String
      @kotlin.jvm.JvmName("getIdentifier")
        get() = _builder.identifier
      @kotlin.jvm.JvmName("setIdentifier")
        set(value) {
        _builder.identifier = value
      }
    /**
     * <code>optional string identifier = 1;</code>
     * @return This builder for chaining.
     */
    public fun clearIdentifier() {
      _builder.clearIdentifier()
    }
    /**
     * <code>optional string identifier = 1;</code>
     * @return Whether the identifier field is set.
     * @return This builder for chaining.
     */
    public fun hasIdentifier(): kotlin.Boolean {
      return _builder.hasIdentifier()
    }

    /**
     * `optional double seconds_remaining = 2;`
     */
    public var secondsRemaining: kotlin.Double
      @kotlin.jvm.JvmName("getSecondsRemaining")
        get() = _builder.secondsRemaining
      @kotlin.jvm.JvmName("setSecondsRemaining")
        set(value) {
        _builder.secondsRemaining = value
      }
    /**
     * <code>optional double seconds_remaining = 2;</code>
     * @return This builder for chaining.
     */
    public fun clearSecondsRemaining() {
      _builder.clearSecondsRemaining()
    }
    /**
     * <code>optional double seconds_remaining = 2;</code>
     * @return Whether the secondsRemaining field is set.
     * @return This builder for chaining.
     */
    public fun hasSecondsRemaining(): kotlin.Boolean {
      return _builder.hasSecondsRemaining()
    }

    /**
     * `optional string type = 3;`
     */
    public var type: kotlin.String
      @kotlin.jvm.JvmName("getType")
        get() = _builder.type
      @kotlin.jvm.JvmName("setType")
        set(value) {
        _builder.type = value
      }
    /**
     * <code>optional string type = 3;</code>
     * @return This builder for chaining.
     */
    public fun clearType() {
      _builder.clearType()
    }
    /**
     * <code>optional string type = 3;</code>
     * @return Whether the type field is set.
     * @return This builder for chaining.
     */
    public fun hasType(): kotlin.Boolean {
      return _builder.hasType()
    }

    /**
     * `optional double multiplier = 4;`
     */
    public var multiplier: kotlin.Double
      @kotlin.jvm.JvmName("getMultiplier")
        get() = _builder.multiplier
      @kotlin.jvm.JvmName("setMultiplier")
        set(value) {
        _builder.multiplier = value
      }
    /**
     * <code>optional double multiplier = 4;</code>
     * @return This builder for chaining.
     */
    public fun clearMultiplier() {
      _builder.clearMultiplier()
    }
    /**
     * <code>optional double multiplier = 4;</code>
     * @return Whether the multiplier field is set.
     * @return This builder for chaining.
     */
    public fun hasMultiplier(): kotlin.Boolean {
      return _builder.hasMultiplier()
    }

    /**
     * `optional string subtitle = 5;`
     */
    public var subtitle: kotlin.String
      @kotlin.jvm.JvmName("getSubtitle")
        get() = _builder.subtitle
      @kotlin.jvm.JvmName("setSubtitle")
        set(value) {
        _builder.subtitle = value
      }
    /**
     * <code>optional string subtitle = 5;</code>
     * @return This builder for chaining.
     */
    public fun clearSubtitle() {
      _builder.clearSubtitle()
    }
    /**
     * <code>optional string subtitle = 5;</code>
     * @return Whether the subtitle field is set.
     * @return This builder for chaining.
     */
    public fun hasSubtitle(): kotlin.Boolean {
      return _builder.hasSubtitle()
    }

    /**
     * `optional double start_time = 6;`
     */
    public var startTime: kotlin.Double
      @kotlin.jvm.JvmName("getStartTime")
        get() = _builder.startTime
      @kotlin.jvm.JvmName("setStartTime")
        set(value) {
        _builder.startTime = value
      }
    /**
     * <code>optional double start_time = 6;</code>
     * @return This builder for chaining.
     */
    public fun clearStartTime() {
      _builder.clearStartTime()
    }
    /**
     * <code>optional double start_time = 6;</code>
     * @return Whether the startTime field is set.
     * @return This builder for chaining.
     */
    public fun hasStartTime(): kotlin.Boolean {
      return _builder.hasStartTime()
    }

    /**
     * `optional double duration = 7;`
     */
    public var duration: kotlin.Double
      @kotlin.jvm.JvmName("getDuration")
        get() = _builder.duration
      @kotlin.jvm.JvmName("setDuration")
        set(value) {
        _builder.duration = value
      }
    /**
     * <code>optional double duration = 7;</code>
     * @return This builder for chaining.
     */
    public fun clearDuration() {
      _builder.clearDuration()
    }
    /**
     * <code>optional double duration = 7;</code>
     * @return Whether the duration field is set.
     * @return This builder for chaining.
     */
    public fun hasDuration(): kotlin.Boolean {
      return _builder.hasDuration()
    }

    /**
     * `optional bool cc_only = 8;`
     */
    public var ccOnly: kotlin.Boolean
      @kotlin.jvm.JvmName("getCcOnly")
        get() = _builder.ccOnly
      @kotlin.jvm.JvmName("setCcOnly")
        set(value) {
        _builder.ccOnly = value
      }
    /**
     * <code>optional bool cc_only = 8;</code>
     * @return This builder for chaining.
     */
    public fun clearCcOnly() {
      _builder.clearCcOnly()
    }
    /**
     * <code>optional bool cc_only = 8;</code>
     * @return Whether the ccOnly field is set.
     * @return This builder for chaining.
     */
    public fun hasCcOnly(): kotlin.Boolean {
      return _builder.hasCcOnly()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ei.Ei.EggIncEvent.copy(block: `ei`.EggIncEventKt.Dsl.() -> kotlin.Unit): ei.Ei.EggIncEvent =
  `ei`.EggIncEventKt.Dsl._create(this.toBuilder()).apply { block() }._build()

