// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ei.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ei;

@kotlin.jvm.JvmName("-initializeleaderboardInfo")
public inline fun leaderboardInfo(block: ei.LeaderboardInfoKt.Dsl.() -> kotlin.Unit): ei.Ei.LeaderboardInfo =
  ei.LeaderboardInfoKt.Dsl._create(ei.Ei.LeaderboardInfo.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ei.LeaderboardInfo`
 */
public object LeaderboardInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ei.Ei.LeaderboardInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: ei.Ei.LeaderboardInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): ei.Ei.LeaderboardInfo = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class SeasonsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .ei.LeaderboardInfo.Season seasons = 1;`
     */
     public val seasons: com.google.protobuf.kotlin.DslList<ei.Ei.LeaderboardInfo.Season, SeasonsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.seasonsList
      )
    /**
     * `repeated .ei.LeaderboardInfo.Season seasons = 1;`
     * @param value The seasons to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addSeasons")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.LeaderboardInfo.Season, SeasonsProxy>.add(value: ei.Ei.LeaderboardInfo.Season) {
      _builder.addSeasons(value)
    }
    /**
     * `repeated .ei.LeaderboardInfo.Season seasons = 1;`
     * @param value The seasons to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignSeasons")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ei.Ei.LeaderboardInfo.Season, SeasonsProxy>.plusAssign(value: ei.Ei.LeaderboardInfo.Season) {
      add(value)
    }
    /**
     * `repeated .ei.LeaderboardInfo.Season seasons = 1;`
     * @param values The seasons to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllSeasons")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.LeaderboardInfo.Season, SeasonsProxy>.addAll(values: kotlin.collections.Iterable<ei.Ei.LeaderboardInfo.Season>) {
      _builder.addAllSeasons(values)
    }
    /**
     * `repeated .ei.LeaderboardInfo.Season seasons = 1;`
     * @param values The seasons to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllSeasons")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ei.Ei.LeaderboardInfo.Season, SeasonsProxy>.plusAssign(values: kotlin.collections.Iterable<ei.Ei.LeaderboardInfo.Season>) {
      addAll(values)
    }
    /**
     * `repeated .ei.LeaderboardInfo.Season seasons = 1;`
     * @param index The index to set the value at.
     * @param value The seasons to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setSeasons")
    public operator fun com.google.protobuf.kotlin.DslList<ei.Ei.LeaderboardInfo.Season, SeasonsProxy>.set(index: kotlin.Int, value: ei.Ei.LeaderboardInfo.Season) {
      _builder.setSeasons(index, value)
    }
    /**
     * `repeated .ei.LeaderboardInfo.Season seasons = 1;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearSeasons")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.LeaderboardInfo.Season, SeasonsProxy>.clear() {
      _builder.clearSeasons()
    }


    /**
     * `optional string all_time_scope = 2;`
     */
    public var allTimeScope: kotlin.String
      @JvmName("getAllTimeScope")
      get() = _builder.allTimeScope
      @JvmName("setAllTimeScope")
      set(value) {
        _builder.allTimeScope = value
      }
    /**
     * `optional string all_time_scope = 2;`
     */
    public fun clearAllTimeScope() {
      _builder.clearAllTimeScope()
    }
    /**
     * `optional string all_time_scope = 2;`
     * @return Whether the allTimeScope field is set.
     */
    public fun hasAllTimeScope(): kotlin.Boolean {
      return _builder.hasAllTimeScope()
    }
  }
  @kotlin.jvm.JvmName("-initializeseason")
  public inline fun season(block: ei.LeaderboardInfoKt.SeasonKt.Dsl.() -> kotlin.Unit): ei.Ei.LeaderboardInfo.Season =
    ei.LeaderboardInfoKt.SeasonKt.Dsl._create(ei.Ei.LeaderboardInfo.Season.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `ei.LeaderboardInfo.Season`
   */
  public object SeasonKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: ei.Ei.LeaderboardInfo.Season.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: ei.Ei.LeaderboardInfo.Season.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): ei.Ei.LeaderboardInfo.Season = _builder.build()

      /**
       * `optional string scope = 1;`
       */
      public var scope: kotlin.String
        @JvmName("getScope")
        get() = _builder.scope
        @JvmName("setScope")
        set(value) {
          _builder.scope = value
        }
      /**
       * `optional string scope = 1;`
       */
      public fun clearScope() {
        _builder.clearScope()
      }
      /**
       * `optional string scope = 1;`
       * @return Whether the scope field is set.
       */
      public fun hasScope(): kotlin.Boolean {
        return _builder.hasScope()
      }

      /**
       * `optional string name = 2;`
       */
      public var name: kotlin.String
        @JvmName("getName")
        get() = _builder.name
        @JvmName("setName")
        set(value) {
          _builder.name = value
        }
      /**
       * `optional string name = 2;`
       */
      public fun clearName() {
        _builder.clearName()
      }
      /**
       * `optional string name = 2;`
       * @return Whether the name field is set.
       */
      public fun hasName(): kotlin.Boolean {
        return _builder.hasName()
      }
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ei.Ei.LeaderboardInfo.copy(block: `ei`.LeaderboardInfoKt.Dsl.() -> kotlin.Unit): ei.Ei.LeaderboardInfo =
  `ei`.LeaderboardInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun ei.Ei.LeaderboardInfo.Season.copy(block: `ei`.LeaderboardInfoKt.SeasonKt.Dsl.() -> kotlin.Unit): ei.Ei.LeaderboardInfo.Season =
  `ei`.LeaderboardInfoKt.SeasonKt.Dsl._create(this.toBuilder()).apply { block() }._build()

