// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ei.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ei;

@kotlin.jvm.JvmName("-initializeliveConfig")
public inline fun liveConfig(block: ei.LiveConfigKt.Dsl.() -> kotlin.Unit): ei.Ei.LiveConfig =
  ei.LiveConfigKt.Dsl._create(ei.Ei.LiveConfig.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ei.LiveConfig`
 */
public object LiveConfigKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ei.Ei.LiveConfig.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: ei.Ei.LiveConfig.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): ei.Ei.LiveConfig = _builder.build()

    /**
     * `optional string config_id = 1;`
     */
    public var configId: kotlin.String
      @kotlin.jvm.JvmName("getConfigId")
        get() = _builder.configId
      @kotlin.jvm.JvmName("setConfigId")
        set(value) {
        _builder.configId = value
      }
    /**
     * <code>optional string config_id = 1;</code>
     * @return This builder for chaining.
     */
    public fun clearConfigId() {
      _builder.clearConfigId()
    }
    /**
     * <code>optional string config_id = 1;</code>
     * @return Whether the configId field is set.
     * @return This builder for chaining.
     */
    public fun hasConfigId(): kotlin.Boolean {
      return _builder.hasConfigId()
    }

    /**
     * `optional .ei.LiveConfig.BoostsConfig boosts_config = 2;`
     */
    public var boostsConfig: ei.Ei.LiveConfig.BoostsConfig
      @kotlin.jvm.JvmName("getBoostsConfig")
        get() = _builder.boostsConfig
      @kotlin.jvm.JvmName("setBoostsConfig")
        set(value) {
        _builder.boostsConfig = value
      }
    /**
     * <code>optional .ei.LiveConfig.BoostsConfig boosts_config = 2;</code>
     * @return This builder for chaining.
     */
    public fun clearBoostsConfig() {
      _builder.clearBoostsConfig()
    }
    /**
     * <code>optional .ei.LiveConfig.BoostsConfig boosts_config = 2;</code>
     * @return Whether the boostsConfig field is set.
     * @return This builder for chaining.
     */
    public fun hasBoostsConfig(): kotlin.Boolean {
      return _builder.hasBoostsConfig()
    }

    public val LiveConfigKt.Dsl.boostsConfigOrNull: ei.Ei.LiveConfig.BoostsConfig?
      get() = _builder.boostsConfigOrNull

    /**
     * `optional .ei.LiveConfig.GiftConfig gift_config = 3;`
     */
    public var giftConfig: ei.Ei.LiveConfig.GiftConfig
      @kotlin.jvm.JvmName("getGiftConfig")
        get() = _builder.giftConfig
      @kotlin.jvm.JvmName("setGiftConfig")
        set(value) {
        _builder.giftConfig = value
      }
    /**
     * <code>optional .ei.LiveConfig.GiftConfig gift_config = 3;</code>
     * @return This builder for chaining.
     */
    public fun clearGiftConfig() {
      _builder.clearGiftConfig()
    }
    /**
     * <code>optional .ei.LiveConfig.GiftConfig gift_config = 3;</code>
     * @return Whether the giftConfig field is set.
     * @return This builder for chaining.
     */
    public fun hasGiftConfig(): kotlin.Boolean {
      return _builder.hasGiftConfig()
    }

    public val LiveConfigKt.Dsl.giftConfigOrNull: ei.Ei.LiveConfig.GiftConfig?
      get() = _builder.giftConfigOrNull

    /**
     * `optional .ei.LiveConfig.MiscConfig misc_config = 4;`
     */
    public var miscConfig: ei.Ei.LiveConfig.MiscConfig
      @kotlin.jvm.JvmName("getMiscConfig")
        get() = _builder.miscConfig
      @kotlin.jvm.JvmName("setMiscConfig")
        set(value) {
        _builder.miscConfig = value
      }
    /**
     * <code>optional .ei.LiveConfig.MiscConfig misc_config = 4;</code>
     * @return This builder for chaining.
     */
    public fun clearMiscConfig() {
      _builder.clearMiscConfig()
    }
    /**
     * <code>optional .ei.LiveConfig.MiscConfig misc_config = 4;</code>
     * @return Whether the miscConfig field is set.
     * @return This builder for chaining.
     */
    public fun hasMiscConfig(): kotlin.Boolean {
      return _builder.hasMiscConfig()
    }

    public val LiveConfigKt.Dsl.miscConfigOrNull: ei.Ei.LiveConfig.MiscConfig?
      get() = _builder.miscConfigOrNull

    /**
     * `optional .ei.LiveConfig.HelpConfig help_config = 5;`
     */
    public var helpConfig: ei.Ei.LiveConfig.HelpConfig
      @kotlin.jvm.JvmName("getHelpConfig")
        get() = _builder.helpConfig
      @kotlin.jvm.JvmName("setHelpConfig")
        set(value) {
        _builder.helpConfig = value
      }
    /**
     * <code>optional .ei.LiveConfig.HelpConfig help_config = 5;</code>
     * @return This builder for chaining.
     */
    public fun clearHelpConfig() {
      _builder.clearHelpConfig()
    }
    /**
     * <code>optional .ei.LiveConfig.HelpConfig help_config = 5;</code>
     * @return Whether the helpConfig field is set.
     * @return This builder for chaining.
     */
    public fun hasHelpConfig(): kotlin.Boolean {
      return _builder.hasHelpConfig()
    }

    public val LiveConfigKt.Dsl.helpConfigOrNull: ei.Ei.LiveConfig.HelpConfig?
      get() = _builder.helpConfigOrNull
  }
  @kotlin.jvm.JvmName("-initializeboostsConfig")
  public inline fun boostsConfig(block: ei.LiveConfigKt.BoostsConfigKt.Dsl.() -> kotlin.Unit): ei.Ei.LiveConfig.BoostsConfig =
    ei.LiveConfigKt.BoostsConfigKt.Dsl._create(ei.Ei.LiveConfig.BoostsConfig.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `ei.LiveConfig.BoostsConfig`
   */
  public object BoostsConfigKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: ei.Ei.LiveConfig.BoostsConfig.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: ei.Ei.LiveConfig.BoostsConfig.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): ei.Ei.LiveConfig.BoostsConfig = _builder.build()

      /**
       * An uninstantiable, behaviorless type to represent the field in
       * generics.
       */
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      public class ItemConfigsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
      /**
       * `repeated .ei.LiveConfig.BoostsConfig.ItemConfig item_configs = 1;`
       */
       public val itemConfigs: com.google.protobuf.kotlin.DslList<ei.Ei.LiveConfig.BoostsConfig.ItemConfig, ItemConfigsProxy>
        @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
          _builder.itemConfigsList
        )
      /**
       * <code>repeated .ei.LiveConfig.BoostsConfig.ItemConfig item_configs = 1;</code>
       * @param value The itemConfigs to add.
       * @return This builder for chaining.
       */
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addItemConfigs")
      public fun com.google.protobuf.kotlin.DslList<ei.Ei.LiveConfig.BoostsConfig.ItemConfig, ItemConfigsProxy>.add(value: ei.Ei.LiveConfig.BoostsConfig.ItemConfig) {
        _builder.addItemConfigs(value)
      }
      /**
       * <code>repeated .ei.LiveConfig.BoostsConfig.ItemConfig item_configs = 1;</code>
       * @param value The itemConfigs to add.
       * @return This builder for chaining.
       */
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignItemConfigs")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<ei.Ei.LiveConfig.BoostsConfig.ItemConfig, ItemConfigsProxy>.plusAssign(value: ei.Ei.LiveConfig.BoostsConfig.ItemConfig) {
        add(value)
      }
      /**
       * <code>repeated .ei.LiveConfig.BoostsConfig.ItemConfig item_configs = 1;</code>
       * @param values The itemConfigs to add.
       * @return This builder for chaining.
       */
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllItemConfigs")
      public fun com.google.protobuf.kotlin.DslList<ei.Ei.LiveConfig.BoostsConfig.ItemConfig, ItemConfigsProxy>.addAll(values: kotlin.collections.Iterable<ei.Ei.LiveConfig.BoostsConfig.ItemConfig>) {
        _builder.addAllItemConfigs(values)
      }
      /**
       * <code>repeated .ei.LiveConfig.BoostsConfig.ItemConfig item_configs = 1;</code>
       * @param values The itemConfigs to add.
       * @return This builder for chaining.
       */
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllItemConfigs")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<ei.Ei.LiveConfig.BoostsConfig.ItemConfig, ItemConfigsProxy>.plusAssign(values: kotlin.collections.Iterable<ei.Ei.LiveConfig.BoostsConfig.ItemConfig>) {
        addAll(values)
      }
      /**
       * <code>repeated .ei.LiveConfig.BoostsConfig.ItemConfig item_configs = 1;</code>
       * @param index The index to set the value at.
       * @param value The itemConfigs to set.
       * @return This builder for chaining.
       */
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setItemConfigs")
      public operator fun com.google.protobuf.kotlin.DslList<ei.Ei.LiveConfig.BoostsConfig.ItemConfig, ItemConfigsProxy>.set(index: kotlin.Int, value: ei.Ei.LiveConfig.BoostsConfig.ItemConfig) {
        _builder.setItemConfigs(index, value)
      }
      /**
       * <code>repeated .ei.LiveConfig.BoostsConfig.ItemConfig item_configs = 1;</code>
       * @return This builder for chaining.
       */
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearItemConfigs")
      public fun com.google.protobuf.kotlin.DslList<ei.Ei.LiveConfig.BoostsConfig.ItemConfig, ItemConfigsProxy>.clear() {
        _builder.clearItemConfigs()
      }

      /**
       * `optional double cash_boost_cooloff_time = 2;`
       */
      public var cashBoostCooloffTime: kotlin.Double
        @kotlin.jvm.JvmName("getCashBoostCooloffTime")
          get() = _builder.cashBoostCooloffTime
        @kotlin.jvm.JvmName("setCashBoostCooloffTime")
          set(value) {
          _builder.cashBoostCooloffTime = value
        }
      /**
       * <code>optional double cash_boost_cooloff_time = 2;</code>
       * @return This builder for chaining.
       */
      public fun clearCashBoostCooloffTime() {
        _builder.clearCashBoostCooloffTime()
      }
      /**
       * <code>optional double cash_boost_cooloff_time = 2;</code>
       * @return Whether the cashBoostCooloffTime field is set.
       * @return This builder for chaining.
       */
      public fun hasCashBoostCooloffTime(): kotlin.Boolean {
        return _builder.hasCashBoostCooloffTime()
      }
    }
    @kotlin.jvm.JvmName("-initializeitemConfig")
    public inline fun itemConfig(block: ei.LiveConfigKt.BoostsConfigKt.ItemConfigKt.Dsl.() -> kotlin.Unit): ei.Ei.LiveConfig.BoostsConfig.ItemConfig =
      ei.LiveConfigKt.BoostsConfigKt.ItemConfigKt.Dsl._create(ei.Ei.LiveConfig.BoostsConfig.ItemConfig.newBuilder()).apply { block() }._build()
    /**
     * Protobuf type `ei.LiveConfig.BoostsConfig.ItemConfig`
     */
    public object ItemConfigKt {
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      @com.google.protobuf.kotlin.ProtoDslMarker
      public class Dsl private constructor(
        private val _builder: ei.Ei.LiveConfig.BoostsConfig.ItemConfig.Builder
      ) {
        public companion object {
          @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
          internal fun _create(builder: ei.Ei.LiveConfig.BoostsConfig.ItemConfig.Builder): Dsl = Dsl(builder)
        }

        @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
        internal fun _build(): ei.Ei.LiveConfig.BoostsConfig.ItemConfig = _builder.build()

        /**
         * `optional string boost_id = 1;`
         */
        public var boostId: kotlin.String
          @kotlin.jvm.JvmName("getBoostId")
            get() = _builder.boostId
          @kotlin.jvm.JvmName("setBoostId")
            set(value) {
            _builder.boostId = value
          }
        /**
         * <code>optional string boost_id = 1;</code>
         * @return This builder for chaining.
         */
        public fun clearBoostId() {
          _builder.clearBoostId()
        }
        /**
         * <code>optional string boost_id = 1;</code>
         * @return Whether the boostId field is set.
         * @return This builder for chaining.
         */
        public fun hasBoostId(): kotlin.Boolean {
          return _builder.hasBoostId()
        }

        /**
         * `optional uint32 price = 2;`
         */
        public var price: kotlin.Int
          @kotlin.jvm.JvmName("getPrice")
            get() = _builder.price
          @kotlin.jvm.JvmName("setPrice")
            set(value) {
            _builder.price = value
          }
        /**
         * <code>optional uint32 price = 2;</code>
         * @return This builder for chaining.
         */
        public fun clearPrice() {
          _builder.clearPrice()
        }
        /**
         * <code>optional uint32 price = 2;</code>
         * @return Whether the price field is set.
         * @return This builder for chaining.
         */
        public fun hasPrice(): kotlin.Boolean {
          return _builder.hasPrice()
        }

        /**
         * `optional uint32 token_price = 3;`
         */
        public var tokenPrice: kotlin.Int
          @kotlin.jvm.JvmName("getTokenPrice")
            get() = _builder.tokenPrice
          @kotlin.jvm.JvmName("setTokenPrice")
            set(value) {
            _builder.tokenPrice = value
          }
        /**
         * <code>optional uint32 token_price = 3;</code>
         * @return This builder for chaining.
         */
        public fun clearTokenPrice() {
          _builder.clearTokenPrice()
        }
        /**
         * <code>optional uint32 token_price = 3;</code>
         * @return Whether the tokenPrice field is set.
         * @return This builder for chaining.
         */
        public fun hasTokenPrice(): kotlin.Boolean {
          return _builder.hasTokenPrice()
        }

        /**
         * `optional double se_required = 4;`
         */
        public var seRequired: kotlin.Double
          @kotlin.jvm.JvmName("getSeRequired")
            get() = _builder.seRequired
          @kotlin.jvm.JvmName("setSeRequired")
            set(value) {
            _builder.seRequired = value
          }
        /**
         * <code>optional double se_required = 4;</code>
         * @return This builder for chaining.
         */
        public fun clearSeRequired() {
          _builder.clearSeRequired()
        }
        /**
         * <code>optional double se_required = 4;</code>
         * @return Whether the seRequired field is set.
         * @return This builder for chaining.
         */
        public fun hasSeRequired(): kotlin.Boolean {
          return _builder.hasSeRequired()
        }
      }
    }
  }
  @kotlin.jvm.JvmName("-initializegiftConfig")
  public inline fun giftConfig(block: ei.LiveConfigKt.GiftConfigKt.Dsl.() -> kotlin.Unit): ei.Ei.LiveConfig.GiftConfig =
    ei.LiveConfigKt.GiftConfigKt.Dsl._create(ei.Ei.LiveConfig.GiftConfig.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `ei.LiveConfig.GiftConfig`
   */
  public object GiftConfigKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: ei.Ei.LiveConfig.GiftConfig.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: ei.Ei.LiveConfig.GiftConfig.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): ei.Ei.LiveConfig.GiftConfig = _builder.build()

      /**
       * An uninstantiable, behaviorless type to represent the field in
       * generics.
       */
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      public class GiftConfigsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
      /**
       * `repeated .ei.LiveConfig.GiftConfig.GiftValueConfig gift_configs = 9;`
       */
       public val giftConfigs: com.google.protobuf.kotlin.DslList<ei.Ei.LiveConfig.GiftConfig.GiftValueConfig, GiftConfigsProxy>
        @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
          _builder.giftConfigsList
        )
      /**
       * <code>repeated .ei.LiveConfig.GiftConfig.GiftValueConfig gift_configs = 9;</code>
       * @param value The giftConfigs to add.
       * @return This builder for chaining.
       */
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addGiftConfigs")
      public fun com.google.protobuf.kotlin.DslList<ei.Ei.LiveConfig.GiftConfig.GiftValueConfig, GiftConfigsProxy>.add(value: ei.Ei.LiveConfig.GiftConfig.GiftValueConfig) {
        _builder.addGiftConfigs(value)
      }
      /**
       * <code>repeated .ei.LiveConfig.GiftConfig.GiftValueConfig gift_configs = 9;</code>
       * @param value The giftConfigs to add.
       * @return This builder for chaining.
       */
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignGiftConfigs")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<ei.Ei.LiveConfig.GiftConfig.GiftValueConfig, GiftConfigsProxy>.plusAssign(value: ei.Ei.LiveConfig.GiftConfig.GiftValueConfig) {
        add(value)
      }
      /**
       * <code>repeated .ei.LiveConfig.GiftConfig.GiftValueConfig gift_configs = 9;</code>
       * @param values The giftConfigs to add.
       * @return This builder for chaining.
       */
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllGiftConfigs")
      public fun com.google.protobuf.kotlin.DslList<ei.Ei.LiveConfig.GiftConfig.GiftValueConfig, GiftConfigsProxy>.addAll(values: kotlin.collections.Iterable<ei.Ei.LiveConfig.GiftConfig.GiftValueConfig>) {
        _builder.addAllGiftConfigs(values)
      }
      /**
       * <code>repeated .ei.LiveConfig.GiftConfig.GiftValueConfig gift_configs = 9;</code>
       * @param values The giftConfigs to add.
       * @return This builder for chaining.
       */
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllGiftConfigs")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<ei.Ei.LiveConfig.GiftConfig.GiftValueConfig, GiftConfigsProxy>.plusAssign(values: kotlin.collections.Iterable<ei.Ei.LiveConfig.GiftConfig.GiftValueConfig>) {
        addAll(values)
      }
      /**
       * <code>repeated .ei.LiveConfig.GiftConfig.GiftValueConfig gift_configs = 9;</code>
       * @param index The index to set the value at.
       * @param value The giftConfigs to set.
       * @return This builder for chaining.
       */
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setGiftConfigs")
      public operator fun com.google.protobuf.kotlin.DslList<ei.Ei.LiveConfig.GiftConfig.GiftValueConfig, GiftConfigsProxy>.set(index: kotlin.Int, value: ei.Ei.LiveConfig.GiftConfig.GiftValueConfig) {
        _builder.setGiftConfigs(index, value)
      }
      /**
       * <code>repeated .ei.LiveConfig.GiftConfig.GiftValueConfig gift_configs = 9;</code>
       * @return This builder for chaining.
       */
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearGiftConfigs")
      public fun com.google.protobuf.kotlin.DslList<ei.Ei.LiveConfig.GiftConfig.GiftValueConfig, GiftConfigsProxy>.clear() {
        _builder.clearGiftConfigs()
      }

      /**
       * `optional double gift_mu_min_spent = 10;`
       */
      public var giftMuMinSpent: kotlin.Double
        @kotlin.jvm.JvmName("getGiftMuMinSpent")
          get() = _builder.giftMuMinSpent
        @kotlin.jvm.JvmName("setGiftMuMinSpent")
          set(value) {
          _builder.giftMuMinSpent = value
        }
      /**
       * <code>optional double gift_mu_min_spent = 10;</code>
       * @return This builder for chaining.
       */
      public fun clearGiftMuMinSpent() {
        _builder.clearGiftMuMinSpent()
      }
      /**
       * <code>optional double gift_mu_min_spent = 10;</code>
       * @return Whether the giftMuMinSpent field is set.
       * @return This builder for chaining.
       */
      public fun hasGiftMuMinSpent(): kotlin.Boolean {
        return _builder.hasGiftMuMinSpent()
      }

      /**
       * `optional double gift_mu_max_spent = 11;`
       */
      public var giftMuMaxSpent: kotlin.Double
        @kotlin.jvm.JvmName("getGiftMuMaxSpent")
          get() = _builder.giftMuMaxSpent
        @kotlin.jvm.JvmName("setGiftMuMaxSpent")
          set(value) {
          _builder.giftMuMaxSpent = value
        }
      /**
       * <code>optional double gift_mu_max_spent = 11;</code>
       * @return This builder for chaining.
       */
      public fun clearGiftMuMaxSpent() {
        _builder.clearGiftMuMaxSpent()
      }
      /**
       * <code>optional double gift_mu_max_spent = 11;</code>
       * @return Whether the giftMuMaxSpent field is set.
       * @return This builder for chaining.
       */
      public fun hasGiftMuMaxSpent(): kotlin.Boolean {
        return _builder.hasGiftMuMaxSpent()
      }

      /**
       * `optional double gift_mu_overall_mult = 12;`
       */
      public var giftMuOverallMult: kotlin.Double
        @kotlin.jvm.JvmName("getGiftMuOverallMult")
          get() = _builder.giftMuOverallMult
        @kotlin.jvm.JvmName("setGiftMuOverallMult")
          set(value) {
          _builder.giftMuOverallMult = value
        }
      /**
       * <code>optional double gift_mu_overall_mult = 12;</code>
       * @return This builder for chaining.
       */
      public fun clearGiftMuOverallMult() {
        _builder.clearGiftMuOverallMult()
      }
      /**
       * <code>optional double gift_mu_overall_mult = 12;</code>
       * @return Whether the giftMuOverallMult field is set.
       * @return This builder for chaining.
       */
      public fun hasGiftMuOverallMult(): kotlin.Boolean {
        return _builder.hasGiftMuOverallMult()
      }

      /**
       * `optional .ei.LiveConfig.GiftConfig.GiftMuConfig random_gift_mu_config = 15;`
       */
      public var randomGiftMuConfig: ei.Ei.LiveConfig.GiftConfig.GiftMuConfig
        @kotlin.jvm.JvmName("getRandomGiftMuConfig")
          get() = _builder.randomGiftMuConfig
        @kotlin.jvm.JvmName("setRandomGiftMuConfig")
          set(value) {
          _builder.randomGiftMuConfig = value
        }
      /**
       * <code>optional .ei.LiveConfig.GiftConfig.GiftMuConfig random_gift_mu_config = 15;</code>
       * @return This builder for chaining.
       */
      public fun clearRandomGiftMuConfig() {
        _builder.clearRandomGiftMuConfig()
      }
      /**
       * <code>optional .ei.LiveConfig.GiftConfig.GiftMuConfig random_gift_mu_config = 15;</code>
       * @return Whether the randomGiftMuConfig field is set.
       * @return This builder for chaining.
       */
      public fun hasRandomGiftMuConfig(): kotlin.Boolean {
        return _builder.hasRandomGiftMuConfig()
      }

      public val GiftConfigKt.Dsl.randomGiftMuConfigOrNull: ei.Ei.LiveConfig.GiftConfig.GiftMuConfig?
        get() = _builder.randomGiftMuConfigOrNull

      /**
       * `optional .ei.LiveConfig.GiftConfig.GiftMuConfig video_gift_mu_config = 16;`
       */
      public var videoGiftMuConfig: ei.Ei.LiveConfig.GiftConfig.GiftMuConfig
        @kotlin.jvm.JvmName("getVideoGiftMuConfig")
          get() = _builder.videoGiftMuConfig
        @kotlin.jvm.JvmName("setVideoGiftMuConfig")
          set(value) {
          _builder.videoGiftMuConfig = value
        }
      /**
       * <code>optional .ei.LiveConfig.GiftConfig.GiftMuConfig video_gift_mu_config = 16;</code>
       * @return This builder for chaining.
       */
      public fun clearVideoGiftMuConfig() {
        _builder.clearVideoGiftMuConfig()
      }
      /**
       * <code>optional .ei.LiveConfig.GiftConfig.GiftMuConfig video_gift_mu_config = 16;</code>
       * @return Whether the videoGiftMuConfig field is set.
       * @return This builder for chaining.
       */
      public fun hasVideoGiftMuConfig(): kotlin.Boolean {
        return _builder.hasVideoGiftMuConfig()
      }

      public val GiftConfigKt.Dsl.videoGiftMuConfigOrNull: ei.Ei.LiveConfig.GiftConfig.GiftMuConfig?
        get() = _builder.videoGiftMuConfigOrNull

      /**
       * `optional double package_interval = 1;`
       */
      public var packageInterval: kotlin.Double
        @kotlin.jvm.JvmName("getPackageInterval")
          get() = _builder.packageInterval
        @kotlin.jvm.JvmName("setPackageInterval")
          set(value) {
          _builder.packageInterval = value
        }
      /**
       * <code>optional double package_interval = 1;</code>
       * @return This builder for chaining.
       */
      public fun clearPackageInterval() {
        _builder.clearPackageInterval()
      }
      /**
       * <code>optional double package_interval = 1;</code>
       * @return Whether the packageInterval field is set.
       * @return This builder for chaining.
       */
      public fun hasPackageInterval(): kotlin.Boolean {
        return _builder.hasPackageInterval()
      }

      /**
       * `optional double video_offer_interval = 2;`
       */
      public var videoOfferInterval: kotlin.Double
        @kotlin.jvm.JvmName("getVideoOfferInterval")
          get() = _builder.videoOfferInterval
        @kotlin.jvm.JvmName("setVideoOfferInterval")
          set(value) {
          _builder.videoOfferInterval = value
        }
      /**
       * <code>optional double video_offer_interval = 2;</code>
       * @return This builder for chaining.
       */
      public fun clearVideoOfferInterval() {
        _builder.clearVideoOfferInterval()
      }
      /**
       * <code>optional double video_offer_interval = 2;</code>
       * @return Whether the videoOfferInterval field is set.
       * @return This builder for chaining.
       */
      public fun hasVideoOfferInterval(): kotlin.Boolean {
        return _builder.hasVideoOfferInterval()
      }

      /**
       * `optional double video_offer_interval_contract = 3;`
       */
      public var videoOfferIntervalContract: kotlin.Double
        @kotlin.jvm.JvmName("getVideoOfferIntervalContract")
          get() = _builder.videoOfferIntervalContract
        @kotlin.jvm.JvmName("setVideoOfferIntervalContract")
          set(value) {
          _builder.videoOfferIntervalContract = value
        }
      /**
       * <code>optional double video_offer_interval_contract = 3;</code>
       * @return This builder for chaining.
       */
      public fun clearVideoOfferIntervalContract() {
        _builder.clearVideoOfferIntervalContract()
      }
      /**
       * <code>optional double video_offer_interval_contract = 3;</code>
       * @return Whether the videoOfferIntervalContract field is set.
       * @return This builder for chaining.
       */
      public fun hasVideoOfferIntervalContract(): kotlin.Boolean {
        return _builder.hasVideoOfferIntervalContract()
      }

      /**
       * `optional double video_offer_interval_piggy_full = 4;`
       */
      public var videoOfferIntervalPiggyFull: kotlin.Double
        @kotlin.jvm.JvmName("getVideoOfferIntervalPiggyFull")
          get() = _builder.videoOfferIntervalPiggyFull
        @kotlin.jvm.JvmName("setVideoOfferIntervalPiggyFull")
          set(value) {
          _builder.videoOfferIntervalPiggyFull = value
        }
      /**
       * <code>optional double video_offer_interval_piggy_full = 4;</code>
       * @return This builder for chaining.
       */
      public fun clearVideoOfferIntervalPiggyFull() {
        _builder.clearVideoOfferIntervalPiggyFull()
      }
      /**
       * <code>optional double video_offer_interval_piggy_full = 4;</code>
       * @return Whether the videoOfferIntervalPiggyFull field is set.
       * @return This builder for chaining.
       */
      public fun hasVideoOfferIntervalPiggyFull(): kotlin.Boolean {
        return _builder.hasVideoOfferIntervalPiggyFull()
      }

      /**
       * `optional double video_offer_interval_piggy_extra_full = 5;`
       */
      public var videoOfferIntervalPiggyExtraFull: kotlin.Double
        @kotlin.jvm.JvmName("getVideoOfferIntervalPiggyExtraFull")
          get() = _builder.videoOfferIntervalPiggyExtraFull
        @kotlin.jvm.JvmName("setVideoOfferIntervalPiggyExtraFull")
          set(value) {
          _builder.videoOfferIntervalPiggyExtraFull = value
        }
      /**
       * <code>optional double video_offer_interval_piggy_extra_full = 5;</code>
       * @return This builder for chaining.
       */
      public fun clearVideoOfferIntervalPiggyExtraFull() {
        _builder.clearVideoOfferIntervalPiggyExtraFull()
      }
      /**
       * <code>optional double video_offer_interval_piggy_extra_full = 5;</code>
       * @return Whether the videoOfferIntervalPiggyExtraFull field is set.
       * @return This builder for chaining.
       */
      public fun hasVideoOfferIntervalPiggyExtraFull(): kotlin.Boolean {
        return _builder.hasVideoOfferIntervalPiggyExtraFull()
      }

      /**
       * `optional bool video_reset_on_idle = 14;`
       */
      public var videoResetOnIdle: kotlin.Boolean
        @kotlin.jvm.JvmName("getVideoResetOnIdle")
          get() = _builder.videoResetOnIdle
        @kotlin.jvm.JvmName("setVideoResetOnIdle")
          set(value) {
          _builder.videoResetOnIdle = value
        }
      /**
       * <code>optional bool video_reset_on_idle = 14;</code>
       * @return This builder for chaining.
       */
      public fun clearVideoResetOnIdle() {
        _builder.clearVideoResetOnIdle()
      }
      /**
       * <code>optional bool video_reset_on_idle = 14;</code>
       * @return Whether the videoResetOnIdle field is set.
       * @return This builder for chaining.
       */
      public fun hasVideoResetOnIdle(): kotlin.Boolean {
        return _builder.hasVideoResetOnIdle()
      }

      /**
       * `optional double package_interval_contract = 6;`
       */
      public var packageIntervalContract: kotlin.Double
        @kotlin.jvm.JvmName("getPackageIntervalContract")
          get() = _builder.packageIntervalContract
        @kotlin.jvm.JvmName("setPackageIntervalContract")
          set(value) {
          _builder.packageIntervalContract = value
        }
      /**
       * <code>optional double package_interval_contract = 6;</code>
       * @return This builder for chaining.
       */
      public fun clearPackageIntervalContract() {
        _builder.clearPackageIntervalContract()
      }
      /**
       * <code>optional double package_interval_contract = 6;</code>
       * @return Whether the packageIntervalContract field is set.
       * @return This builder for chaining.
       */
      public fun hasPackageIntervalContract(): kotlin.Boolean {
        return _builder.hasPackageIntervalContract()
      }

      /**
       * `optional double package_interval_piggy_full = 7;`
       */
      public var packageIntervalPiggyFull: kotlin.Double
        @kotlin.jvm.JvmName("getPackageIntervalPiggyFull")
          get() = _builder.packageIntervalPiggyFull
        @kotlin.jvm.JvmName("setPackageIntervalPiggyFull")
          set(value) {
          _builder.packageIntervalPiggyFull = value
        }
      /**
       * <code>optional double package_interval_piggy_full = 7;</code>
       * @return This builder for chaining.
       */
      public fun clearPackageIntervalPiggyFull() {
        _builder.clearPackageIntervalPiggyFull()
      }
      /**
       * <code>optional double package_interval_piggy_full = 7;</code>
       * @return Whether the packageIntervalPiggyFull field is set.
       * @return This builder for chaining.
       */
      public fun hasPackageIntervalPiggyFull(): kotlin.Boolean {
        return _builder.hasPackageIntervalPiggyFull()
      }

      /**
       * `optional double package_interval_piggy_extra_full = 8;`
       */
      public var packageIntervalPiggyExtraFull: kotlin.Double
        @kotlin.jvm.JvmName("getPackageIntervalPiggyExtraFull")
          get() = _builder.packageIntervalPiggyExtraFull
        @kotlin.jvm.JvmName("setPackageIntervalPiggyExtraFull")
          set(value) {
          _builder.packageIntervalPiggyExtraFull = value
        }
      /**
       * <code>optional double package_interval_piggy_extra_full = 8;</code>
       * @return This builder for chaining.
       */
      public fun clearPackageIntervalPiggyExtraFull() {
        _builder.clearPackageIntervalPiggyExtraFull()
      }
      /**
       * <code>optional double package_interval_piggy_extra_full = 8;</code>
       * @return Whether the packageIntervalPiggyExtraFull field is set.
       * @return This builder for chaining.
       */
      public fun hasPackageIntervalPiggyExtraFull(): kotlin.Boolean {
        return _builder.hasPackageIntervalPiggyExtraFull()
      }

      /**
       * `optional bool package_reset_on_idle = 13;`
       */
      public var packageResetOnIdle: kotlin.Boolean
        @kotlin.jvm.JvmName("getPackageResetOnIdle")
          get() = _builder.packageResetOnIdle
        @kotlin.jvm.JvmName("setPackageResetOnIdle")
          set(value) {
          _builder.packageResetOnIdle = value
        }
      /**
       * <code>optional bool package_reset_on_idle = 13;</code>
       * @return This builder for chaining.
       */
      public fun clearPackageResetOnIdle() {
        _builder.clearPackageResetOnIdle()
      }
      /**
       * <code>optional bool package_reset_on_idle = 13;</code>
       * @return Whether the packageResetOnIdle field is set.
       * @return This builder for chaining.
       */
      public fun hasPackageResetOnIdle(): kotlin.Boolean {
        return _builder.hasPackageResetOnIdle()
      }
    }
    @kotlin.jvm.JvmName("-initializegiftValueConfig")
    public inline fun giftValueConfig(block: ei.LiveConfigKt.GiftConfigKt.GiftValueConfigKt.Dsl.() -> kotlin.Unit): ei.Ei.LiveConfig.GiftConfig.GiftValueConfig =
      ei.LiveConfigKt.GiftConfigKt.GiftValueConfigKt.Dsl._create(ei.Ei.LiveConfig.GiftConfig.GiftValueConfig.newBuilder()).apply { block() }._build()
    /**
     * Protobuf type `ei.LiveConfig.GiftConfig.GiftValueConfig`
     */
    public object GiftValueConfigKt {
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      @com.google.protobuf.kotlin.ProtoDslMarker
      public class Dsl private constructor(
        private val _builder: ei.Ei.LiveConfig.GiftConfig.GiftValueConfig.Builder
      ) {
        public companion object {
          @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
          internal fun _create(builder: ei.Ei.LiveConfig.GiftConfig.GiftValueConfig.Builder): Dsl = Dsl(builder)
        }

        @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
        internal fun _build(): ei.Ei.LiveConfig.GiftConfig.GiftValueConfig = _builder.build()

        /**
         * `optional string gift_id = 1;`
         */
        public var giftId: kotlin.String
          @kotlin.jvm.JvmName("getGiftId")
            get() = _builder.giftId
          @kotlin.jvm.JvmName("setGiftId")
            set(value) {
            _builder.giftId = value
          }
        /**
         * <code>optional string gift_id = 1;</code>
         * @return This builder for chaining.
         */
        public fun clearGiftId() {
          _builder.clearGiftId()
        }
        /**
         * <code>optional string gift_id = 1;</code>
         * @return Whether the giftId field is set.
         * @return This builder for chaining.
         */
        public fun hasGiftId(): kotlin.Boolean {
          return _builder.hasGiftId()
        }

        /**
         * `optional double amount = 4;`
         */
        public var amount: kotlin.Double
          @kotlin.jvm.JvmName("getAmount")
            get() = _builder.amount
          @kotlin.jvm.JvmName("setAmount")
            set(value) {
            _builder.amount = value
          }
        /**
         * <code>optional double amount = 4;</code>
         * @return This builder for chaining.
         */
        public fun clearAmount() {
          _builder.clearAmount()
        }
        /**
         * <code>optional double amount = 4;</code>
         * @return Whether the amount field is set.
         * @return This builder for chaining.
         */
        public fun hasAmount(): kotlin.Boolean {
          return _builder.hasAmount()
        }

        /**
         * `optional double rand_min = 2;`
         */
        public var randMin: kotlin.Double
          @kotlin.jvm.JvmName("getRandMin")
            get() = _builder.randMin
          @kotlin.jvm.JvmName("setRandMin")
            set(value) {
            _builder.randMin = value
          }
        /**
         * <code>optional double rand_min = 2;</code>
         * @return This builder for chaining.
         */
        public fun clearRandMin() {
          _builder.clearRandMin()
        }
        /**
         * <code>optional double rand_min = 2;</code>
         * @return Whether the randMin field is set.
         * @return This builder for chaining.
         */
        public fun hasRandMin(): kotlin.Boolean {
          return _builder.hasRandMin()
        }

        /**
         * `optional double rand_max = 3;`
         */
        public var randMax: kotlin.Double
          @kotlin.jvm.JvmName("getRandMax")
            get() = _builder.randMax
          @kotlin.jvm.JvmName("setRandMax")
            set(value) {
            _builder.randMax = value
          }
        /**
         * <code>optional double rand_max = 3;</code>
         * @return This builder for chaining.
         */
        public fun clearRandMax() {
          _builder.clearRandMax()
        }
        /**
         * <code>optional double rand_max = 3;</code>
         * @return Whether the randMax field is set.
         * @return This builder for chaining.
         */
        public fun hasRandMax(): kotlin.Boolean {
          return _builder.hasRandMax()
        }

        /**
         * `optional double video_min = 5;`
         */
        public var videoMin: kotlin.Double
          @kotlin.jvm.JvmName("getVideoMin")
            get() = _builder.videoMin
          @kotlin.jvm.JvmName("setVideoMin")
            set(value) {
            _builder.videoMin = value
          }
        /**
         * <code>optional double video_min = 5;</code>
         * @return This builder for chaining.
         */
        public fun clearVideoMin() {
          _builder.clearVideoMin()
        }
        /**
         * <code>optional double video_min = 5;</code>
         * @return Whether the videoMin field is set.
         * @return This builder for chaining.
         */
        public fun hasVideoMin(): kotlin.Boolean {
          return _builder.hasVideoMin()
        }

        /**
         * `optional double video_max = 6;`
         */
        public var videoMax: kotlin.Double
          @kotlin.jvm.JvmName("getVideoMax")
            get() = _builder.videoMax
          @kotlin.jvm.JvmName("setVideoMax")
            set(value) {
            _builder.videoMax = value
          }
        /**
         * <code>optional double video_max = 6;</code>
         * @return This builder for chaining.
         */
        public fun clearVideoMax() {
          _builder.clearVideoMax()
        }
        /**
         * <code>optional double video_max = 6;</code>
         * @return Whether the videoMax field is set.
         * @return This builder for chaining.
         */
        public fun hasVideoMax(): kotlin.Boolean {
          return _builder.hasVideoMax()
        }
      }
    }
    @kotlin.jvm.JvmName("-initializegiftMuConfig")
    public inline fun giftMuConfig(block: ei.LiveConfigKt.GiftConfigKt.GiftMuConfigKt.Dsl.() -> kotlin.Unit): ei.Ei.LiveConfig.GiftConfig.GiftMuConfig =
      ei.LiveConfigKt.GiftConfigKt.GiftMuConfigKt.Dsl._create(ei.Ei.LiveConfig.GiftConfig.GiftMuConfig.newBuilder()).apply { block() }._build()
    /**
     * Protobuf type `ei.LiveConfig.GiftConfig.GiftMuConfig`
     */
    public object GiftMuConfigKt {
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      @com.google.protobuf.kotlin.ProtoDslMarker
      public class Dsl private constructor(
        private val _builder: ei.Ei.LiveConfig.GiftConfig.GiftMuConfig.Builder
      ) {
        public companion object {
          @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
          internal fun _create(builder: ei.Ei.LiveConfig.GiftConfig.GiftMuConfig.Builder): Dsl = Dsl(builder)
        }

        @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
        internal fun _build(): ei.Ei.LiveConfig.GiftConfig.GiftMuConfig = _builder.build()

        /**
         * `optional double min_spent = 1;`
         */
        public var minSpent: kotlin.Double
          @kotlin.jvm.JvmName("getMinSpent")
            get() = _builder.minSpent
          @kotlin.jvm.JvmName("setMinSpent")
            set(value) {
            _builder.minSpent = value
          }
        /**
         * <code>optional double min_spent = 1;</code>
         * @return This builder for chaining.
         */
        public fun clearMinSpent() {
          _builder.clearMinSpent()
        }
        /**
         * <code>optional double min_spent = 1;</code>
         * @return Whether the minSpent field is set.
         * @return This builder for chaining.
         */
        public fun hasMinSpent(): kotlin.Boolean {
          return _builder.hasMinSpent()
        }

        /**
         * `optional double max_spent = 2;`
         */
        public var maxSpent: kotlin.Double
          @kotlin.jvm.JvmName("getMaxSpent")
            get() = _builder.maxSpent
          @kotlin.jvm.JvmName("setMaxSpent")
            set(value) {
            _builder.maxSpent = value
          }
        /**
         * <code>optional double max_spent = 2;</code>
         * @return This builder for chaining.
         */
        public fun clearMaxSpent() {
          _builder.clearMaxSpent()
        }
        /**
         * <code>optional double max_spent = 2;</code>
         * @return Whether the maxSpent field is set.
         * @return This builder for chaining.
         */
        public fun hasMaxSpent(): kotlin.Boolean {
          return _builder.hasMaxSpent()
        }

        /**
         * `optional double overall_mult = 3;`
         */
        public var overallMult: kotlin.Double
          @kotlin.jvm.JvmName("getOverallMult")
            get() = _builder.overallMult
          @kotlin.jvm.JvmName("setOverallMult")
            set(value) {
            _builder.overallMult = value
          }
        /**
         * <code>optional double overall_mult = 3;</code>
         * @return This builder for chaining.
         */
        public fun clearOverallMult() {
          _builder.clearOverallMult()
        }
        /**
         * <code>optional double overall_mult = 3;</code>
         * @return Whether the overallMult field is set.
         * @return This builder for chaining.
         */
        public fun hasOverallMult(): kotlin.Boolean {
          return _builder.hasOverallMult()
        }
      }
    }
  }
  @kotlin.jvm.JvmName("-initializemiscConfig")
  public inline fun miscConfig(block: ei.LiveConfigKt.MiscConfigKt.Dsl.() -> kotlin.Unit): ei.Ei.LiveConfig.MiscConfig =
    ei.LiveConfigKt.MiscConfigKt.Dsl._create(ei.Ei.LiveConfig.MiscConfig.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `ei.LiveConfig.MiscConfig`
   */
  public object MiscConfigKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: ei.Ei.LiveConfig.MiscConfig.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: ei.Ei.LiveConfig.MiscConfig.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): ei.Ei.LiveConfig.MiscConfig = _builder.build()

      /**
       * `optional bool ask_to_track = 1;`
       */
      public var askToTrack: kotlin.Boolean
        @kotlin.jvm.JvmName("getAskToTrack")
          get() = _builder.askToTrack
        @kotlin.jvm.JvmName("setAskToTrack")
          set(value) {
          _builder.askToTrack = value
        }
      /**
       * <code>optional bool ask_to_track = 1;</code>
       * @return This builder for chaining.
       */
      public fun clearAskToTrack() {
        _builder.clearAskToTrack()
      }
      /**
       * <code>optional bool ask_to_track = 1;</code>
       * @return Whether the askToTrack field is set.
       * @return This builder for chaining.
       */
      public fun hasAskToTrack(): kotlin.Boolean {
        return _builder.hasAskToTrack()
      }

      /**
       * `optional double ask_to_track_min_soul_eggs = 2;`
       */
      public var askToTrackMinSoulEggs: kotlin.Double
        @kotlin.jvm.JvmName("getAskToTrackMinSoulEggs")
          get() = _builder.askToTrackMinSoulEggs
        @kotlin.jvm.JvmName("setAskToTrackMinSoulEggs")
          set(value) {
          _builder.askToTrackMinSoulEggs = value
        }
      /**
       * <code>optional double ask_to_track_min_soul_eggs = 2;</code>
       * @return This builder for chaining.
       */
      public fun clearAskToTrackMinSoulEggs() {
        _builder.clearAskToTrackMinSoulEggs()
      }
      /**
       * <code>optional double ask_to_track_min_soul_eggs = 2;</code>
       * @return Whether the askToTrackMinSoulEggs field is set.
       * @return This builder for chaining.
       */
      public fun hasAskToTrackMinSoulEggs(): kotlin.Boolean {
        return _builder.hasAskToTrackMinSoulEggs()
      }

      /**
       * `optional string ask_to_track_message = 3;`
       */
      public var askToTrackMessage: kotlin.String
        @kotlin.jvm.JvmName("getAskToTrackMessage")
          get() = _builder.askToTrackMessage
        @kotlin.jvm.JvmName("setAskToTrackMessage")
          set(value) {
          _builder.askToTrackMessage = value
        }
      /**
       * <code>optional string ask_to_track_message = 3;</code>
       * @return This builder for chaining.
       */
      public fun clearAskToTrackMessage() {
        _builder.clearAskToTrackMessage()
      }
      /**
       * <code>optional string ask_to_track_message = 3;</code>
       * @return Whether the askToTrackMessage field is set.
       * @return This builder for chaining.
       */
      public fun hasAskToTrackMessage(): kotlin.Boolean {
        return _builder.hasAskToTrackMessage()
      }

      /**
       * `optional bool ask_to_track_show_pre_dialog = 4;`
       */
      public var askToTrackShowPreDialog: kotlin.Boolean
        @kotlin.jvm.JvmName("getAskToTrackShowPreDialog")
          get() = _builder.askToTrackShowPreDialog
        @kotlin.jvm.JvmName("setAskToTrackShowPreDialog")
          set(value) {
          _builder.askToTrackShowPreDialog = value
        }
      /**
       * <code>optional bool ask_to_track_show_pre_dialog = 4;</code>
       * @return This builder for chaining.
       */
      public fun clearAskToTrackShowPreDialog() {
        _builder.clearAskToTrackShowPreDialog()
      }
      /**
       * <code>optional bool ask_to_track_show_pre_dialog = 4;</code>
       * @return Whether the askToTrackShowPreDialog field is set.
       * @return This builder for chaining.
       */
      public fun hasAskToTrackShowPreDialog(): kotlin.Boolean {
        return _builder.hasAskToTrackShowPreDialog()
      }

      /**
       * `optional bool ask_to_track_after_privacy = 5;`
       */
      public var askToTrackAfterPrivacy: kotlin.Boolean
        @kotlin.jvm.JvmName("getAskToTrackAfterPrivacy")
          get() = _builder.askToTrackAfterPrivacy
        @kotlin.jvm.JvmName("setAskToTrackAfterPrivacy")
          set(value) {
          _builder.askToTrackAfterPrivacy = value
        }
      /**
       * <code>optional bool ask_to_track_after_privacy = 5;</code>
       * @return This builder for chaining.
       */
      public fun clearAskToTrackAfterPrivacy() {
        _builder.clearAskToTrackAfterPrivacy()
      }
      /**
       * <code>optional bool ask_to_track_after_privacy = 5;</code>
       * @return Whether the askToTrackAfterPrivacy field is set.
       * @return This builder for chaining.
       */
      public fun hasAskToTrackAfterPrivacy(): kotlin.Boolean {
        return _builder.hasAskToTrackAfterPrivacy()
      }

      /**
       * `optional double chicken_run_boost_percentage = 6;`
       */
      public var chickenRunBoostPercentage: kotlin.Double
        @kotlin.jvm.JvmName("getChickenRunBoostPercentage")
          get() = _builder.chickenRunBoostPercentage
        @kotlin.jvm.JvmName("setChickenRunBoostPercentage")
          set(value) {
          _builder.chickenRunBoostPercentage = value
        }
      /**
       * <code>optional double chicken_run_boost_percentage = 6;</code>
       * @return This builder for chaining.
       */
      public fun clearChickenRunBoostPercentage() {
        _builder.clearChickenRunBoostPercentage()
      }
      /**
       * <code>optional double chicken_run_boost_percentage = 6;</code>
       * @return Whether the chickenRunBoostPercentage field is set.
       * @return This builder for chaining.
       */
      public fun hasChickenRunBoostPercentage(): kotlin.Boolean {
        return _builder.hasChickenRunBoostPercentage()
      }

      /**
       * `optional uint32 shells_intro_tickets = 7;`
       */
      public var shellsIntroTickets: kotlin.Int
        @kotlin.jvm.JvmName("getShellsIntroTickets")
          get() = _builder.shellsIntroTickets
        @kotlin.jvm.JvmName("setShellsIntroTickets")
          set(value) {
          _builder.shellsIntroTickets = value
        }
      /**
       * <code>optional uint32 shells_intro_tickets = 7;</code>
       * @return This builder for chaining.
       */
      public fun clearShellsIntroTickets() {
        _builder.clearShellsIntroTickets()
      }
      /**
       * <code>optional uint32 shells_intro_tickets = 7;</code>
       * @return Whether the shellsIntroTickets field is set.
       * @return This builder for chaining.
       */
      public fun hasShellsIntroTickets(): kotlin.Boolean {
        return _builder.hasShellsIntroTickets()
      }

      /**
       * `optional uint32 shells_max_free_chicken_configs = 8;`
       */
      public var shellsMaxFreeChickenConfigs: kotlin.Int
        @kotlin.jvm.JvmName("getShellsMaxFreeChickenConfigs")
          get() = _builder.shellsMaxFreeChickenConfigs
        @kotlin.jvm.JvmName("setShellsMaxFreeChickenConfigs")
          set(value) {
          _builder.shellsMaxFreeChickenConfigs = value
        }
      /**
       * <code>optional uint32 shells_max_free_chicken_configs = 8;</code>
       * @return This builder for chaining.
       */
      public fun clearShellsMaxFreeChickenConfigs() {
        _builder.clearShellsMaxFreeChickenConfigs()
      }
      /**
       * <code>optional uint32 shells_max_free_chicken_configs = 8;</code>
       * @return Whether the shellsMaxFreeChickenConfigs field is set.
       * @return This builder for chaining.
       */
      public fun hasShellsMaxFreeChickenConfigs(): kotlin.Boolean {
        return _builder.hasShellsMaxFreeChickenConfigs()
      }

      /**
       * `optional uint32 shells_intro_alert_threshold = 9;`
       */
      public var shellsIntroAlertThreshold: kotlin.Int
        @kotlin.jvm.JvmName("getShellsIntroAlertThreshold")
          get() = _builder.shellsIntroAlertThreshold
        @kotlin.jvm.JvmName("setShellsIntroAlertThreshold")
          set(value) {
          _builder.shellsIntroAlertThreshold = value
        }
      /**
       * <code>optional uint32 shells_intro_alert_threshold = 9;</code>
       * @return This builder for chaining.
       */
      public fun clearShellsIntroAlertThreshold() {
        _builder.clearShellsIntroAlertThreshold()
      }
      /**
       * <code>optional uint32 shells_intro_alert_threshold = 9;</code>
       * @return Whether the shellsIntroAlertThreshold field is set.
       * @return This builder for chaining.
       */
      public fun hasShellsIntroAlertThreshold(): kotlin.Boolean {
        return _builder.hasShellsIntroAlertThreshold()
      }

      /**
       * `optional uint32 shells_lighting_controls_price = 14 [default = 175];`
       */
      public var shellsLightingControlsPrice: kotlin.Int
        @kotlin.jvm.JvmName("getShellsLightingControlsPrice")
          get() = _builder.shellsLightingControlsPrice
        @kotlin.jvm.JvmName("setShellsLightingControlsPrice")
          set(value) {
          _builder.shellsLightingControlsPrice = value
        }
      /**
       * <code>optional uint32 shells_lighting_controls_price = 14 [default = 175];</code>
       * @return This builder for chaining.
       */
      public fun clearShellsLightingControlsPrice() {
        _builder.clearShellsLightingControlsPrice()
      }
      /**
       * <code>optional uint32 shells_lighting_controls_price = 14 [default = 175];</code>
       * @return Whether the shellsLightingControlsPrice field is set.
       * @return This builder for chaining.
       */
      public fun hasShellsLightingControlsPrice(): kotlin.Boolean {
        return _builder.hasShellsLightingControlsPrice()
      }

      /**
       * `optional double contracts_expert_league_min_soul_power = 10;`
       */
      public var contractsExpertLeagueMinSoulPower: kotlin.Double
        @kotlin.jvm.JvmName("getContractsExpertLeagueMinSoulPower")
          get() = _builder.contractsExpertLeagueMinSoulPower
        @kotlin.jvm.JvmName("setContractsExpertLeagueMinSoulPower")
          set(value) {
          _builder.contractsExpertLeagueMinSoulPower = value
        }
      /**
       * <code>optional double contracts_expert_league_min_soul_power = 10;</code>
       * @return This builder for chaining.
       */
      public fun clearContractsExpertLeagueMinSoulPower() {
        _builder.clearContractsExpertLeagueMinSoulPower()
      }
      /**
       * <code>optional double contracts_expert_league_min_soul_power = 10;</code>
       * @return Whether the contractsExpertLeagueMinSoulPower field is set.
       * @return This builder for chaining.
       */
      public fun hasContractsExpertLeagueMinSoulPower(): kotlin.Boolean {
        return _builder.hasContractsExpertLeagueMinSoulPower()
      }

      /**
       * `optional double new_player_event_duration = 11;`
       */
      public var newPlayerEventDuration: kotlin.Double
        @kotlin.jvm.JvmName("getNewPlayerEventDuration")
          get() = _builder.newPlayerEventDuration
        @kotlin.jvm.JvmName("setNewPlayerEventDuration")
          set(value) {
          _builder.newPlayerEventDuration = value
        }
      /**
       * <code>optional double new_player_event_duration = 11;</code>
       * @return This builder for chaining.
       */
      public fun clearNewPlayerEventDuration() {
        _builder.clearNewPlayerEventDuration()
      }
      /**
       * <code>optional double new_player_event_duration = 11;</code>
       * @return Whether the newPlayerEventDuration field is set.
       * @return This builder for chaining.
       */
      public fun hasNewPlayerEventDuration(): kotlin.Boolean {
        return _builder.hasNewPlayerEventDuration()
      }

      /**
       * `optional bool contracts_club_available = 12;`
       */
      public var contractsClubAvailable: kotlin.Boolean
        @kotlin.jvm.JvmName("getContractsClubAvailable")
          get() = _builder.contractsClubAvailable
        @kotlin.jvm.JvmName("setContractsClubAvailable")
          set(value) {
          _builder.contractsClubAvailable = value
        }
      /**
       * <code>optional bool contracts_club_available = 12;</code>
       * @return This builder for chaining.
       */
      public fun clearContractsClubAvailable() {
        _builder.clearContractsClubAvailable()
      }
      /**
       * <code>optional bool contracts_club_available = 12;</code>
       * @return Whether the contractsClubAvailable field is set.
       * @return This builder for chaining.
       */
      public fun hasContractsClubAvailable(): kotlin.Boolean {
        return _builder.hasContractsClubAvailable()
      }

      /**
       * `optional bool contracts_beta = 13;`
       */
      public var contractsBeta: kotlin.Boolean
        @kotlin.jvm.JvmName("getContractsBeta")
          get() = _builder.contractsBeta
        @kotlin.jvm.JvmName("setContractsBeta")
          set(value) {
          _builder.contractsBeta = value
        }
      /**
       * <code>optional bool contracts_beta = 13;</code>
       * @return This builder for chaining.
       */
      public fun clearContractsBeta() {
        _builder.clearContractsBeta()
      }
      /**
       * <code>optional bool contracts_beta = 13;</code>
       * @return Whether the contractsBeta field is set.
       * @return This builder for chaining.
       */
      public fun hasContractsBeta(): kotlin.Boolean {
        return _builder.hasContractsBeta()
      }

      /**
       * `optional bool season_rewards_enabled = 15;`
       */
      public var seasonRewardsEnabled: kotlin.Boolean
        @kotlin.jvm.JvmName("getSeasonRewardsEnabled")
          get() = _builder.seasonRewardsEnabled
        @kotlin.jvm.JvmName("setSeasonRewardsEnabled")
          set(value) {
          _builder.seasonRewardsEnabled = value
        }
      /**
       * <code>optional bool season_rewards_enabled = 15;</code>
       * @return This builder for chaining.
       */
      public fun clearSeasonRewardsEnabled() {
        _builder.clearSeasonRewardsEnabled()
      }
      /**
       * <code>optional bool season_rewards_enabled = 15;</code>
       * @return Whether the seasonRewardsEnabled field is set.
       * @return This builder for chaining.
       */
      public fun hasSeasonRewardsEnabled(): kotlin.Boolean {
        return _builder.hasSeasonRewardsEnabled()
      }
    }
  }
  @kotlin.jvm.JvmName("-initializehelpConfig")
  public inline fun helpConfig(block: ei.LiveConfigKt.HelpConfigKt.Dsl.() -> kotlin.Unit): ei.Ei.LiveConfig.HelpConfig =
    ei.LiveConfigKt.HelpConfigKt.Dsl._create(ei.Ei.LiveConfig.HelpConfig.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `ei.LiveConfig.HelpConfig`
   */
  public object HelpConfigKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: ei.Ei.LiveConfig.HelpConfig.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: ei.Ei.LiveConfig.HelpConfig.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): ei.Ei.LiveConfig.HelpConfig = _builder.build()

      /**
       * An uninstantiable, behaviorless type to represent the field in
       * generics.
       */
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      public class VideoInfosProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
      /**
       * `repeated .ei.LiveConfig.HelpConfig.HowToVideoInfo video_infos = 1;`
       */
       public val videoInfos: com.google.protobuf.kotlin.DslList<ei.Ei.LiveConfig.HelpConfig.HowToVideoInfo, VideoInfosProxy>
        @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
          _builder.videoInfosList
        )
      /**
       * <code>repeated .ei.LiveConfig.HelpConfig.HowToVideoInfo video_infos = 1;</code>
       * @param value The videoInfos to add.
       * @return This builder for chaining.
       */
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addVideoInfos")
      public fun com.google.protobuf.kotlin.DslList<ei.Ei.LiveConfig.HelpConfig.HowToVideoInfo, VideoInfosProxy>.add(value: ei.Ei.LiveConfig.HelpConfig.HowToVideoInfo) {
        _builder.addVideoInfos(value)
      }
      /**
       * <code>repeated .ei.LiveConfig.HelpConfig.HowToVideoInfo video_infos = 1;</code>
       * @param value The videoInfos to add.
       * @return This builder for chaining.
       */
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignVideoInfos")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<ei.Ei.LiveConfig.HelpConfig.HowToVideoInfo, VideoInfosProxy>.plusAssign(value: ei.Ei.LiveConfig.HelpConfig.HowToVideoInfo) {
        add(value)
      }
      /**
       * <code>repeated .ei.LiveConfig.HelpConfig.HowToVideoInfo video_infos = 1;</code>
       * @param values The videoInfos to add.
       * @return This builder for chaining.
       */
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllVideoInfos")
      public fun com.google.protobuf.kotlin.DslList<ei.Ei.LiveConfig.HelpConfig.HowToVideoInfo, VideoInfosProxy>.addAll(values: kotlin.collections.Iterable<ei.Ei.LiveConfig.HelpConfig.HowToVideoInfo>) {
        _builder.addAllVideoInfos(values)
      }
      /**
       * <code>repeated .ei.LiveConfig.HelpConfig.HowToVideoInfo video_infos = 1;</code>
       * @param values The videoInfos to add.
       * @return This builder for chaining.
       */
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllVideoInfos")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<ei.Ei.LiveConfig.HelpConfig.HowToVideoInfo, VideoInfosProxy>.plusAssign(values: kotlin.collections.Iterable<ei.Ei.LiveConfig.HelpConfig.HowToVideoInfo>) {
        addAll(values)
      }
      /**
       * <code>repeated .ei.LiveConfig.HelpConfig.HowToVideoInfo video_infos = 1;</code>
       * @param index The index to set the value at.
       * @param value The videoInfos to set.
       * @return This builder for chaining.
       */
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setVideoInfos")
      public operator fun com.google.protobuf.kotlin.DslList<ei.Ei.LiveConfig.HelpConfig.HowToVideoInfo, VideoInfosProxy>.set(index: kotlin.Int, value: ei.Ei.LiveConfig.HelpConfig.HowToVideoInfo) {
        _builder.setVideoInfos(index, value)
      }
      /**
       * <code>repeated .ei.LiveConfig.HelpConfig.HowToVideoInfo video_infos = 1;</code>
       * @return This builder for chaining.
       */
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearVideoInfos")
      public fun com.google.protobuf.kotlin.DslList<ei.Ei.LiveConfig.HelpConfig.HowToVideoInfo, VideoInfosProxy>.clear() {
        _builder.clearVideoInfos()
      }
    }
    @kotlin.jvm.JvmName("-initializehowToVideoInfo")
    public inline fun howToVideoInfo(block: ei.LiveConfigKt.HelpConfigKt.HowToVideoInfoKt.Dsl.() -> kotlin.Unit): ei.Ei.LiveConfig.HelpConfig.HowToVideoInfo =
      ei.LiveConfigKt.HelpConfigKt.HowToVideoInfoKt.Dsl._create(ei.Ei.LiveConfig.HelpConfig.HowToVideoInfo.newBuilder()).apply { block() }._build()
    /**
     * Protobuf type `ei.LiveConfig.HelpConfig.HowToVideoInfo`
     */
    public object HowToVideoInfoKt {
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      @com.google.protobuf.kotlin.ProtoDslMarker
      public class Dsl private constructor(
        private val _builder: ei.Ei.LiveConfig.HelpConfig.HowToVideoInfo.Builder
      ) {
        public companion object {
          @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
          internal fun _create(builder: ei.Ei.LiveConfig.HelpConfig.HowToVideoInfo.Builder): Dsl = Dsl(builder)
        }

        @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
        internal fun _build(): ei.Ei.LiveConfig.HelpConfig.HowToVideoInfo = _builder.build()

        /**
         * `optional .ei.LiveConfig.HelpConfig.HowToVideoInfo.Type type = 6;`
         */
        public var type: ei.Ei.LiveConfig.HelpConfig.HowToVideoInfo.Type
          @kotlin.jvm.JvmName("getType")
            get() = _builder.type
          @kotlin.jvm.JvmName("setType")
            set(value) {
            _builder.type = value
          }
        /**
         * <code>optional .ei.LiveConfig.HelpConfig.HowToVideoInfo.Type type = 6;</code>
         * @return This builder for chaining.
         */
        public fun clearType() {
          _builder.clearType()
        }
        /**
         * <code>optional .ei.LiveConfig.HelpConfig.HowToVideoInfo.Type type = 6;</code>
         * @return Whether the type field is set.
         * @return This builder for chaining.
         */
        public fun hasType(): kotlin.Boolean {
          return _builder.hasType()
        }

        /**
         * `optional string name = 1;`
         */
        public var name: kotlin.String
          @kotlin.jvm.JvmName("getName")
            get() = _builder.name
          @kotlin.jvm.JvmName("setName")
            set(value) {
            _builder.name = value
          }
        /**
         * <code>optional string name = 1;</code>
         * @return This builder for chaining.
         */
        public fun clearName() {
          _builder.clearName()
        }
        /**
         * <code>optional string name = 1;</code>
         * @return Whether the name field is set.
         * @return This builder for chaining.
         */
        public fun hasName(): kotlin.Boolean {
          return _builder.hasName()
        }

        /**
         * `optional string description = 2;`
         */
        public var description: kotlin.String
          @kotlin.jvm.JvmName("getDescription")
            get() = _builder.description
          @kotlin.jvm.JvmName("setDescription")
            set(value) {
            _builder.description = value
          }
        /**
         * <code>optional string description = 2;</code>
         * @return This builder for chaining.
         */
        public fun clearDescription() {
          _builder.clearDescription()
        }
        /**
         * <code>optional string description = 2;</code>
         * @return Whether the description field is set.
         * @return This builder for chaining.
         */
        public fun hasDescription(): kotlin.Boolean {
          return _builder.hasDescription()
        }

        /**
         * `optional string duration = 5;`
         */
        public var duration: kotlin.String
          @kotlin.jvm.JvmName("getDuration")
            get() = _builder.duration
          @kotlin.jvm.JvmName("setDuration")
            set(value) {
            _builder.duration = value
          }
        /**
         * <code>optional string duration = 5;</code>
         * @return This builder for chaining.
         */
        public fun clearDuration() {
          _builder.clearDuration()
        }
        /**
         * <code>optional string duration = 5;</code>
         * @return Whether the duration field is set.
         * @return This builder for chaining.
         */
        public fun hasDuration(): kotlin.Boolean {
          return _builder.hasDuration()
        }

        /**
         * `optional string url = 3;`
         */
        public var url: kotlin.String
          @kotlin.jvm.JvmName("getUrl")
            get() = _builder.url
          @kotlin.jvm.JvmName("setUrl")
            set(value) {
            _builder.url = value
          }
        /**
         * <code>optional string url = 3;</code>
         * @return This builder for chaining.
         */
        public fun clearUrl() {
          _builder.clearUrl()
        }
        /**
         * <code>optional string url = 3;</code>
         * @return Whether the url field is set.
         * @return This builder for chaining.
         */
        public fun hasUrl(): kotlin.Boolean {
          return _builder.hasUrl()
        }

        /**
         * `optional double soul_eggs = 4;`
         */
        public var soulEggs: kotlin.Double
          @kotlin.jvm.JvmName("getSoulEggs")
            get() = _builder.soulEggs
          @kotlin.jvm.JvmName("setSoulEggs")
            set(value) {
            _builder.soulEggs = value
          }
        /**
         * <code>optional double soul_eggs = 4;</code>
         * @return This builder for chaining.
         */
        public fun clearSoulEggs() {
          _builder.clearSoulEggs()
        }
        /**
         * <code>optional double soul_eggs = 4;</code>
         * @return Whether the soulEggs field is set.
         * @return This builder for chaining.
         */
        public fun hasSoulEggs(): kotlin.Boolean {
          return _builder.hasSoulEggs()
        }
      }
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ei.Ei.LiveConfig.copy(block: `ei`.LiveConfigKt.Dsl.() -> kotlin.Unit): ei.Ei.LiveConfig =
  `ei`.LiveConfigKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun ei.Ei.LiveConfig.BoostsConfig.copy(block: `ei`.LiveConfigKt.BoostsConfigKt.Dsl.() -> kotlin.Unit): ei.Ei.LiveConfig.BoostsConfig =
  `ei`.LiveConfigKt.BoostsConfigKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun ei.Ei.LiveConfig.BoostsConfig.ItemConfig.copy(block: `ei`.LiveConfigKt.BoostsConfigKt.ItemConfigKt.Dsl.() -> kotlin.Unit): ei.Ei.LiveConfig.BoostsConfig.ItemConfig =
  `ei`.LiveConfigKt.BoostsConfigKt.ItemConfigKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun ei.Ei.LiveConfig.GiftConfig.copy(block: `ei`.LiveConfigKt.GiftConfigKt.Dsl.() -> kotlin.Unit): ei.Ei.LiveConfig.GiftConfig =
  `ei`.LiveConfigKt.GiftConfigKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun ei.Ei.LiveConfig.GiftConfig.GiftValueConfig.copy(block: `ei`.LiveConfigKt.GiftConfigKt.GiftValueConfigKt.Dsl.() -> kotlin.Unit): ei.Ei.LiveConfig.GiftConfig.GiftValueConfig =
  `ei`.LiveConfigKt.GiftConfigKt.GiftValueConfigKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun ei.Ei.LiveConfig.GiftConfig.GiftMuConfig.copy(block: `ei`.LiveConfigKt.GiftConfigKt.GiftMuConfigKt.Dsl.() -> kotlin.Unit): ei.Ei.LiveConfig.GiftConfig.GiftMuConfig =
  `ei`.LiveConfigKt.GiftConfigKt.GiftMuConfigKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val ei.Ei.LiveConfig.GiftConfigOrBuilder.randomGiftMuConfigOrNull: ei.Ei.LiveConfig.GiftConfig.GiftMuConfig?
  get() = if (hasRandomGiftMuConfig()) getRandomGiftMuConfig() else null

public val ei.Ei.LiveConfig.GiftConfigOrBuilder.videoGiftMuConfigOrNull: ei.Ei.LiveConfig.GiftConfig.GiftMuConfig?
  get() = if (hasVideoGiftMuConfig()) getVideoGiftMuConfig() else null

@kotlin.jvm.JvmSynthetic
public inline fun ei.Ei.LiveConfig.MiscConfig.copy(block: `ei`.LiveConfigKt.MiscConfigKt.Dsl.() -> kotlin.Unit): ei.Ei.LiveConfig.MiscConfig =
  `ei`.LiveConfigKt.MiscConfigKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun ei.Ei.LiveConfig.HelpConfig.copy(block: `ei`.LiveConfigKt.HelpConfigKt.Dsl.() -> kotlin.Unit): ei.Ei.LiveConfig.HelpConfig =
  `ei`.LiveConfigKt.HelpConfigKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun ei.Ei.LiveConfig.HelpConfig.HowToVideoInfo.copy(block: `ei`.LiveConfigKt.HelpConfigKt.HowToVideoInfoKt.Dsl.() -> kotlin.Unit): ei.Ei.LiveConfig.HelpConfig.HowToVideoInfo =
  `ei`.LiveConfigKt.HelpConfigKt.HowToVideoInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val ei.Ei.LiveConfigOrBuilder.boostsConfigOrNull: ei.Ei.LiveConfig.BoostsConfig?
  get() = if (hasBoostsConfig()) getBoostsConfig() else null

public val ei.Ei.LiveConfigOrBuilder.giftConfigOrNull: ei.Ei.LiveConfig.GiftConfig?
  get() = if (hasGiftConfig()) getGiftConfig() else null

public val ei.Ei.LiveConfigOrBuilder.miscConfigOrNull: ei.Ei.LiveConfig.MiscConfig?
  get() = if (hasMiscConfig()) getMiscConfig() else null

public val ei.Ei.LiveConfigOrBuilder.helpConfigOrNull: ei.Ei.LiveConfig.HelpConfig?
  get() = if (hasHelpConfig()) getHelpConfig() else null

