//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: ei.proto

package ei;

@kotlin.jvm.JvmName("-initializemailDB")
public inline fun mailDB(block: ei.MailDBKt.Dsl.() -> kotlin.Unit): ei.Ei.MailDB =
  ei.MailDBKt.Dsl._create(ei.Ei.MailDB.newBuilder()).apply { block() }._build()
public object MailDBKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ei.Ei.MailDB.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ei.Ei.MailDB.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ei.Ei.MailDB = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class MailProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .ei.InGameMail mail = 1;</code>
     */
     public val mail: com.google.protobuf.kotlin.DslList<ei.Ei.InGameMail, MailProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getMailList()
      )
    /**
     * <code>repeated .ei.InGameMail mail = 1;</code>
     * @param value The mail to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addMail")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.InGameMail, MailProxy>.add(value: ei.Ei.InGameMail) {
      _builder.addMail(value)
    }
    /**
     * <code>repeated .ei.InGameMail mail = 1;</code>
     * @param value The mail to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignMail")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ei.Ei.InGameMail, MailProxy>.plusAssign(value: ei.Ei.InGameMail) {
      add(value)
    }
    /**
     * <code>repeated .ei.InGameMail mail = 1;</code>
     * @param values The mail to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllMail")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.InGameMail, MailProxy>.addAll(values: kotlin.collections.Iterable<ei.Ei.InGameMail>) {
      _builder.addAllMail(values)
    }
    /**
     * <code>repeated .ei.InGameMail mail = 1;</code>
     * @param values The mail to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllMail")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ei.Ei.InGameMail, MailProxy>.plusAssign(values: kotlin.collections.Iterable<ei.Ei.InGameMail>) {
      addAll(values)
    }
    /**
     * <code>repeated .ei.InGameMail mail = 1;</code>
     * @param index The index to set the value at.
     * @param value The mail to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setMail")
    public operator fun com.google.protobuf.kotlin.DslList<ei.Ei.InGameMail, MailProxy>.set(index: kotlin.Int, value: ei.Ei.InGameMail) {
      _builder.setMail(index, value)
    }
    /**
     * <code>repeated .ei.InGameMail mail = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearMail")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.InGameMail, MailProxy>.clear() {
      _builder.clearMail()
    }


    /**
     * <code>optional bytes tips_db_data = 2;</code>
     */
    public var tipsDbData: com.google.protobuf.ByteString
      @JvmName("getTipsDbData")
      get() = _builder.getTipsDbData()
      @JvmName("setTipsDbData")
      set(value) {
        _builder.setTipsDbData(value)
      }
    /**
     * <code>optional bytes tips_db_data = 2;</code>
     */
    public fun clearTipsDbData() {
      _builder.clearTipsDbData()
    }
    /**
     * <code>optional bytes tips_db_data = 2;</code>
     * @return Whether the tipsDbData field is set.
     */
    public fun hasTipsDbData(): kotlin.Boolean {
      return _builder.hasTipsDbData()
    }

    /**
     * <code>optional string tips_checksum = 3;</code>
     */
    public var tipsChecksum: kotlin.String
      @JvmName("getTipsChecksum")
      get() = _builder.getTipsChecksum()
      @JvmName("setTipsChecksum")
      set(value) {
        _builder.setTipsChecksum(value)
      }
    /**
     * <code>optional string tips_checksum = 3;</code>
     */
    public fun clearTipsChecksum() {
      _builder.clearTipsChecksum()
    }
    /**
     * <code>optional string tips_checksum = 3;</code>
     * @return Whether the tipsChecksum field is set.
     */
    public fun hasTipsChecksum(): kotlin.Boolean {
      return _builder.hasTipsChecksum()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ei.Ei.MailDB.copy(block: ei.MailDBKt.Dsl.() -> kotlin.Unit): ei.Ei.MailDB =
  ei.MailDBKt.Dsl._create(this.toBuilder()).apply { block() }._build()

