//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: ei.proto

package ei;

@kotlin.jvm.JvmName("-initializemissionInfo")
public inline fun missionInfo(block: ei.MissionInfoKt.Dsl.() -> kotlin.Unit): ei.Ei.MissionInfo =
  ei.MissionInfoKt.Dsl._create(ei.Ei.MissionInfo.newBuilder()).apply { block() }._build()
public object MissionInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ei.Ei.MissionInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ei.Ei.MissionInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ei.Ei.MissionInfo = _builder.build()

    /**
     * <code>optional .ei.MissionInfo.Spaceship ship = 1;</code>
     */
    public var ship: ei.Ei.MissionInfo.Spaceship
      @JvmName("getShip")
      get() = _builder.getShip()
      @JvmName("setShip")
      set(value) {
        _builder.setShip(value)
      }
    /**
     * <code>optional .ei.MissionInfo.Spaceship ship = 1;</code>
     */
    public fun clearShip() {
      _builder.clearShip()
    }
    /**
     * <code>optional .ei.MissionInfo.Spaceship ship = 1;</code>
     * @return Whether the ship field is set.
     */
    public fun hasShip(): kotlin.Boolean {
      return _builder.hasShip()
    }

    /**
     * <code>optional .ei.MissionInfo.Status status = 2;</code>
     */
    public var status: ei.Ei.MissionInfo.Status
      @JvmName("getStatus")
      get() = _builder.getStatus()
      @JvmName("setStatus")
      set(value) {
        _builder.setStatus(value)
      }
    /**
     * <code>optional .ei.MissionInfo.Status status = 2;</code>
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }
    /**
     * <code>optional .ei.MissionInfo.Status status = 2;</code>
     * @return Whether the status field is set.
     */
    public fun hasStatus(): kotlin.Boolean {
      return _builder.hasStatus()
    }

    /**
     * <code>optional .ei.MissionInfo.DurationType duration_type = 3;</code>
     */
    public var durationType: ei.Ei.MissionInfo.DurationType
      @JvmName("getDurationType")
      get() = _builder.getDurationType()
      @JvmName("setDurationType")
      set(value) {
        _builder.setDurationType(value)
      }
    /**
     * <code>optional .ei.MissionInfo.DurationType duration_type = 3;</code>
     */
    public fun clearDurationType() {
      _builder.clearDurationType()
    }
    /**
     * <code>optional .ei.MissionInfo.DurationType duration_type = 3;</code>
     * @return Whether the durationType field is set.
     */
    public fun hasDurationType(): kotlin.Boolean {
      return _builder.hasDurationType()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class FuelProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .ei.MissionInfo.Fuel fuel = 4;</code>
     */
     public val fuel: com.google.protobuf.kotlin.DslList<ei.Ei.MissionInfo.Fuel, FuelProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getFuelList()
      )
    /**
     * <code>repeated .ei.MissionInfo.Fuel fuel = 4;</code>
     * @param value The fuel to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addFuel")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.MissionInfo.Fuel, FuelProxy>.add(value: ei.Ei.MissionInfo.Fuel) {
      _builder.addFuel(value)
    }
    /**
     * <code>repeated .ei.MissionInfo.Fuel fuel = 4;</code>
     * @param value The fuel to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignFuel")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ei.Ei.MissionInfo.Fuel, FuelProxy>.plusAssign(value: ei.Ei.MissionInfo.Fuel) {
      add(value)
    }
    /**
     * <code>repeated .ei.MissionInfo.Fuel fuel = 4;</code>
     * @param values The fuel to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllFuel")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.MissionInfo.Fuel, FuelProxy>.addAll(values: kotlin.collections.Iterable<ei.Ei.MissionInfo.Fuel>) {
      _builder.addAllFuel(values)
    }
    /**
     * <code>repeated .ei.MissionInfo.Fuel fuel = 4;</code>
     * @param values The fuel to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllFuel")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ei.Ei.MissionInfo.Fuel, FuelProxy>.plusAssign(values: kotlin.collections.Iterable<ei.Ei.MissionInfo.Fuel>) {
      addAll(values)
    }
    /**
     * <code>repeated .ei.MissionInfo.Fuel fuel = 4;</code>
     * @param index The index to set the value at.
     * @param value The fuel to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setFuel")
    public operator fun com.google.protobuf.kotlin.DslList<ei.Ei.MissionInfo.Fuel, FuelProxy>.set(index: kotlin.Int, value: ei.Ei.MissionInfo.Fuel) {
      _builder.setFuel(index, value)
    }
    /**
     * <code>repeated .ei.MissionInfo.Fuel fuel = 4;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearFuel")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.MissionInfo.Fuel, FuelProxy>.clear() {
      _builder.clearFuel()
    }


    /**
     * <code>optional uint32 level = 12;</code>
     */
    public var level: kotlin.Int
      @JvmName("getLevel")
      get() = _builder.getLevel()
      @JvmName("setLevel")
      set(value) {
        _builder.setLevel(value)
      }
    /**
     * <code>optional uint32 level = 12;</code>
     */
    public fun clearLevel() {
      _builder.clearLevel()
    }
    /**
     * <code>optional uint32 level = 12;</code>
     * @return Whether the level field is set.
     */
    public fun hasLevel(): kotlin.Boolean {
      return _builder.hasLevel()
    }

    /**
     * <code>optional double duration_seconds = 5;</code>
     */
    public var durationSeconds: kotlin.Double
      @JvmName("getDurationSeconds")
      get() = _builder.getDurationSeconds()
      @JvmName("setDurationSeconds")
      set(value) {
        _builder.setDurationSeconds(value)
      }
    /**
     * <code>optional double duration_seconds = 5;</code>
     */
    public fun clearDurationSeconds() {
      _builder.clearDurationSeconds()
    }
    /**
     * <code>optional double duration_seconds = 5;</code>
     * @return Whether the durationSeconds field is set.
     */
    public fun hasDurationSeconds(): kotlin.Boolean {
      return _builder.hasDurationSeconds()
    }

    /**
     * <code>optional uint32 capacity = 9;</code>
     */
    public var capacity: kotlin.Int
      @JvmName("getCapacity")
      get() = _builder.getCapacity()
      @JvmName("setCapacity")
      set(value) {
        _builder.setCapacity(value)
      }
    /**
     * <code>optional uint32 capacity = 9;</code>
     */
    public fun clearCapacity() {
      _builder.clearCapacity()
    }
    /**
     * <code>optional uint32 capacity = 9;</code>
     * @return Whether the capacity field is set.
     */
    public fun hasCapacity(): kotlin.Boolean {
      return _builder.hasCapacity()
    }

    /**
     * <code>optional double quality_bump = 11;</code>
     */
    public var qualityBump: kotlin.Double
      @JvmName("getQualityBump")
      get() = _builder.getQualityBump()
      @JvmName("setQualityBump")
      set(value) {
        _builder.setQualityBump(value)
      }
    /**
     * <code>optional double quality_bump = 11;</code>
     */
    public fun clearQualityBump() {
      _builder.clearQualityBump()
    }
    /**
     * <code>optional double quality_bump = 11;</code>
     * @return Whether the qualityBump field is set.
     */
    public fun hasQualityBump(): kotlin.Boolean {
      return _builder.hasQualityBump()
    }

    /**
     * <code>optional double seconds_remaining = 6;</code>
     */
    public var secondsRemaining: kotlin.Double
      @JvmName("getSecondsRemaining")
      get() = _builder.getSecondsRemaining()
      @JvmName("setSecondsRemaining")
      set(value) {
        _builder.setSecondsRemaining(value)
      }
    /**
     * <code>optional double seconds_remaining = 6;</code>
     */
    public fun clearSecondsRemaining() {
      _builder.clearSecondsRemaining()
    }
    /**
     * <code>optional double seconds_remaining = 6;</code>
     * @return Whether the secondsRemaining field is set.
     */
    public fun hasSecondsRemaining(): kotlin.Boolean {
      return _builder.hasSecondsRemaining()
    }

    /**
     * <code>optional double start_time_derived = 8;</code>
     */
    public var startTimeDerived: kotlin.Double
      @JvmName("getStartTimeDerived")
      get() = _builder.getStartTimeDerived()
      @JvmName("setStartTimeDerived")
      set(value) {
        _builder.setStartTimeDerived(value)
      }
    /**
     * <code>optional double start_time_derived = 8;</code>
     */
    public fun clearStartTimeDerived() {
      _builder.clearStartTimeDerived()
    }
    /**
     * <code>optional double start_time_derived = 8;</code>
     * @return Whether the startTimeDerived field is set.
     */
    public fun hasStartTimeDerived(): kotlin.Boolean {
      return _builder.hasStartTimeDerived()
    }

    /**
     * <code>optional string mission_log = 10;</code>
     */
    public var missionLog: kotlin.String
      @JvmName("getMissionLog")
      get() = _builder.getMissionLog()
      @JvmName("setMissionLog")
      set(value) {
        _builder.setMissionLog(value)
      }
    /**
     * <code>optional string mission_log = 10;</code>
     */
    public fun clearMissionLog() {
      _builder.clearMissionLog()
    }
    /**
     * <code>optional string mission_log = 10;</code>
     * @return Whether the missionLog field is set.
     */
    public fun hasMissionLog(): kotlin.Boolean {
      return _builder.hasMissionLog()
    }

    /**
     * <code>optional string identifier = 7;</code>
     */
    public var identifier: kotlin.String
      @JvmName("getIdentifier")
      get() = _builder.getIdentifier()
      @JvmName("setIdentifier")
      set(value) {
        _builder.setIdentifier(value)
      }
    /**
     * <code>optional string identifier = 7;</code>
     */
    public fun clearIdentifier() {
      _builder.clearIdentifier()
    }
    /**
     * <code>optional string identifier = 7;</code>
     * @return Whether the identifier field is set.
     */
    public fun hasIdentifier(): kotlin.Boolean {
      return _builder.hasIdentifier()
    }
  }
  @kotlin.jvm.JvmName("-initializefuel")
  public inline fun fuel(block: ei.MissionInfoKt.FuelKt.Dsl.() -> kotlin.Unit): ei.Ei.MissionInfo.Fuel =
    ei.MissionInfoKt.FuelKt.Dsl._create(ei.Ei.MissionInfo.Fuel.newBuilder()).apply { block() }._build()
  public object FuelKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: ei.Ei.MissionInfo.Fuel.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: ei.Ei.MissionInfo.Fuel.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): ei.Ei.MissionInfo.Fuel = _builder.build()

      /**
       * <code>optional .ei.Egg egg = 1;</code>
       */
      public var egg: ei.Ei.Egg
        @JvmName("getEgg")
        get() = _builder.getEgg()
        @JvmName("setEgg")
        set(value) {
          _builder.setEgg(value)
        }
      /**
       * <code>optional .ei.Egg egg = 1;</code>
       */
      public fun clearEgg() {
        _builder.clearEgg()
      }
      /**
       * <code>optional .ei.Egg egg = 1;</code>
       * @return Whether the egg field is set.
       */
      public fun hasEgg(): kotlin.Boolean {
        return _builder.hasEgg()
      }

      /**
       * <code>optional double amount = 2;</code>
       */
      public var amount: kotlin.Double
        @JvmName("getAmount")
        get() = _builder.getAmount()
        @JvmName("setAmount")
        set(value) {
          _builder.setAmount(value)
        }
      /**
       * <code>optional double amount = 2;</code>
       */
      public fun clearAmount() {
        _builder.clearAmount()
      }
      /**
       * <code>optional double amount = 2;</code>
       * @return Whether the amount field is set.
       */
      public fun hasAmount(): kotlin.Boolean {
        return _builder.hasAmount()
      }
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ei.Ei.MissionInfo.copy(block: ei.MissionInfoKt.Dsl.() -> kotlin.Unit): ei.Ei.MissionInfo =
  ei.MissionInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun ei.Ei.MissionInfo.Fuel.copy(block: ei.MissionInfoKt.FuelKt.Dsl.() -> kotlin.Unit): ei.Ei.MissionInfo.Fuel =
  ei.MissionInfoKt.FuelKt.Dsl._create(this.toBuilder()).apply { block() }._build()

