// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ei.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ei;

@kotlin.jvm.JvmName("-initializeshellsActionBatch")
public inline fun shellsActionBatch(block: ei.ShellsActionBatchKt.Dsl.() -> kotlin.Unit): ei.Ei.ShellsActionBatch =
  ei.ShellsActionBatchKt.Dsl._create(ei.Ei.ShellsActionBatch.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ei.ShellsActionBatch`
 */
public object ShellsActionBatchKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ei.Ei.ShellsActionBatch.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: ei.Ei.ShellsActionBatch.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): ei.Ei.ShellsActionBatch = _builder.build()

    /**
     * `optional .ei.BasicRequestInfo rinfo = 1;`
     */
    public var rinfo: ei.Ei.BasicRequestInfo
      @JvmName("getRinfo")
      get() = _builder.rinfo
      @JvmName("setRinfo")
      set(value) {
        _builder.rinfo = value
      }
    /**
     * `optional .ei.BasicRequestInfo rinfo = 1;`
     */
    public fun clearRinfo() {
      _builder.clearRinfo()
    }
    /**
     * `optional .ei.BasicRequestInfo rinfo = 1;`
     * @return Whether the rinfo field is set.
     */
    public fun hasRinfo(): kotlin.Boolean {
      return _builder.hasRinfo()
    }

    public val ShellsActionBatchKt.Dsl.rinfoOrNull: ei.Ei.BasicRequestInfo?
      get() = _builder.rinfoOrNull

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ActionsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .ei.ShellsActionLog actions = 2;`
     */
     public val actions: com.google.protobuf.kotlin.DslList<ei.Ei.ShellsActionLog, ActionsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.actionsList
      )
    /**
     * `repeated .ei.ShellsActionLog actions = 2;`
     * @param value The actions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addActions")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.ShellsActionLog, ActionsProxy>.add(value: ei.Ei.ShellsActionLog) {
      _builder.addActions(value)
    }
    /**
     * `repeated .ei.ShellsActionLog actions = 2;`
     * @param value The actions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignActions")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ei.Ei.ShellsActionLog, ActionsProxy>.plusAssign(value: ei.Ei.ShellsActionLog) {
      add(value)
    }
    /**
     * `repeated .ei.ShellsActionLog actions = 2;`
     * @param values The actions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllActions")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.ShellsActionLog, ActionsProxy>.addAll(values: kotlin.collections.Iterable<ei.Ei.ShellsActionLog>) {
      _builder.addAllActions(values)
    }
    /**
     * `repeated .ei.ShellsActionLog actions = 2;`
     * @param values The actions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllActions")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ei.Ei.ShellsActionLog, ActionsProxy>.plusAssign(values: kotlin.collections.Iterable<ei.Ei.ShellsActionLog>) {
      addAll(values)
    }
    /**
     * `repeated .ei.ShellsActionLog actions = 2;`
     * @param index The index to set the value at.
     * @param value The actions to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setActions")
    public operator fun com.google.protobuf.kotlin.DslList<ei.Ei.ShellsActionLog, ActionsProxy>.set(index: kotlin.Int, value: ei.Ei.ShellsActionLog) {
      _builder.setActions(index, value)
    }
    /**
     * `repeated .ei.ShellsActionLog actions = 2;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearActions")
    public fun com.google.protobuf.kotlin.DslList<ei.Ei.ShellsActionLog, ActionsProxy>.clear() {
      _builder.clearActions()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ei.Ei.ShellsActionBatch.copy(block: `ei`.ShellsActionBatchKt.Dsl.() -> kotlin.Unit): ei.Ei.ShellsActionBatch =
  `ei`.ShellsActionBatchKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val ei.Ei.ShellsActionBatchOrBuilder.rinfoOrNull: ei.Ei.BasicRequestInfo?
  get() = if (hasRinfo()) getRinfo() else null

