// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ei.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ei;

@kotlin.jvm.JvmName("-initializetranslationPlaceholder")
public inline fun translationPlaceholder(block: ei.TranslationPlaceholderKt.Dsl.() -> kotlin.Unit): ei.Ei.TranslationPlaceholder =
  ei.TranslationPlaceholderKt.Dsl._create(ei.Ei.TranslationPlaceholder.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ei.TranslationPlaceholder`
 */
public object TranslationPlaceholderKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ei.Ei.TranslationPlaceholder.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: ei.Ei.TranslationPlaceholder.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): ei.Ei.TranslationPlaceholder = _builder.build()

    /**
     * `optional uint32 index = 1;`
     */
    public var index: kotlin.Int
      @kotlin.jvm.JvmName("getIndex")
        get() = _builder.index
      @kotlin.jvm.JvmName("setIndex")
        set(value) {
        _builder.index = value
      }
    /**
     * `optional uint32 index = 1;`
     */
    public fun clearIndex() {
      _builder.clearIndex()
    }
    /**
     * `optional uint32 index = 1;`
     * @return Whether the index field is set.
     */
    public fun hasIndex(): kotlin.Boolean {
      return _builder.hasIndex()
    }

    /**
     * `optional .ei.TranslationPlaceholderType type = 2;`
     */
    public var type: ei.Ei.TranslationPlaceholderType
      @kotlin.jvm.JvmName("getType")
        get() = _builder.type
      @kotlin.jvm.JvmName("setType")
        set(value) {
        _builder.type = value
      }
    /**
     * `optional .ei.TranslationPlaceholderType type = 2;`
     */
    public fun clearType() {
      _builder.clearType()
    }
    /**
     * `optional .ei.TranslationPlaceholderType type = 2;`
     * @return Whether the type field is set.
     */
    public fun hasType(): kotlin.Boolean {
      return _builder.hasType()
    }

    /**
     * `optional string sample = 3;`
     */
    public var sample: kotlin.String
      @kotlin.jvm.JvmName("getSample")
        get() = _builder.sample
      @kotlin.jvm.JvmName("setSample")
        set(value) {
        _builder.sample = value
      }
    /**
     * `optional string sample = 3;`
     */
    public fun clearSample() {
      _builder.clearSample()
    }
    /**
     * `optional string sample = 3;`
     * @return Whether the sample field is set.
     */
    public fun hasSample(): kotlin.Boolean {
      return _builder.hasSample()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ei.Ei.TranslationPlaceholder.copy(block: `ei`.TranslationPlaceholderKt.Dsl.() -> kotlin.Unit): ei.Ei.TranslationPlaceholder =
  `ei`.TranslationPlaceholderKt.Dsl._create(this.toBuilder()).apply { block() }._build()

